In [2]:
import pandas as pd
import numpy as np

In [3]:
#Open Foursquare and Yelp DataFrames
foursquare_venues_new=pd.read_csv('foursquare_venues_new.csv',index_col=[0])
yelp_venues=pd.read_csv('yelp_venues.csv',index_col=[0])

In [4]:
#Take care of duplicating nbhoods
yelp_venues_new=yelp_venues.replace('Chelsea', 'Chelsea M')

In [5]:
#Create the combined DataFrame for venues
venues=pd.concat([foursquare_venues_new, yelp_venues_new], axis=0, ignore_index=True)

In [6]:
venues

,Neighborhood,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Marble Hill,Bikram Yoga,40.876844,-73.906204,Yoga Studio
1,Marble Hill,Arturo's,40.874412,-73.910271,Pizza Place
2,Marble Hill,Tibbett Diner,40.880404,-73.908937,Diner
3,Marble Hill,Dunkin',40.877136,-73.906666,Donut Shop
4,Marble Hill,Starbucks,40.877531,-73.905582,Coffee Shop
...,...,...,...,...,...
19126,Elm Park,New Ranchito Deli,40.631000,-74.147110,Food Delivery Services
19127,Elm Park,The New Dinette,40.636612,-74.133980,Restaurants
19128,Elm Park,Baskin-Robbins,40.626640,-74.135071,Ice Cream & Frozen Yogurt
19129,Elm Park,Sin Fronters Deli,40.632770,-74.134330,Delis
19130,Elm Park,Exotic,40.626718,-74.131770,Vape Shops

In [7]:
#Number of venues that appear several times
venues.duplicated(subset=['Venue Latitude', 'Venue Longitude']).sum()

3173

In [8]:
#Duplicates that appear in same neighborhood several times (category may vary) -need to be removed
venues.duplicated(subset=['Neighborhood','Venue Latitude','Venue Longitude']).sum()

104

In [9]:
#Remove venues that are listed more than once in one nbhood
venues_no_dups=venues.drop_duplicates(subset=['Neighborhood','Venue Latitude','Venue Longitude']).copy()

In [10]:
#Number of venues that appear more than in one neighborhood. 3059/18986 (around 16%)
venues_no_dups.duplicated(subset=['Venue Latitude', 'Venue Longitude']).sum()

3069

In [11]:
#Lets clean up category names for most popular categories 
#Chinese venues
chinese=venues_no_dups[venues_no_dups['Venue Category'].str.contains('Chin')]

In [12]:
chinese.groupby(['Venue Category']).count()

                    Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Chinese                      529    529             529              529
Chinese Restaurant           230    230             230              230

In [13]:
venues_no_dups=venues_no_dups.replace('Chinese', 'Chinese Restaurant')

In [14]:
#Pizza venues
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Pizza')].groupby(['Venue Category']).count()

                Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Pizza                    524    524             524              524
Pizza Place              437    437             437              437

In [15]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(['Pizza', 'Pizza Place'],'Pizza Restaurant'))

In [16]:
#Coffee venues
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Coffe')].groupby(['Venue Category']).count()

                   Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Coffee & Tea                454    454             454              454
Coffee Roasteries             9      9               9                9
Coffee Shop                 311    311             311              311

In [17]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(['Coffee & Tea', 'Coffee Roasteries', 'Coffee Shop'],'Coffee Restaurant'))

In [18]:
#Bakeries
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Baker')].groupby(['Venue Category']).count()

                Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Bakeries                 407    407             407              407
Bakery                   227    227             227              227

In [19]:
venues_no_dups=venues_no_dups.replace('Bakeries','Bakery')

In [20]:
#Italian Restaurants
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Ital')].groupby(['Venue Category']).count()

                    Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Italian                      248    248             248              248
Italian Restaurant           310    310             310              310

In [21]:
venues_no_dups=venues_no_dups.replace('Italian','Italian Restaurant')

In [22]:
#Deli
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Del')].groupby(['Venue Category']).count()

                        Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Deli / Bodega                    280    280             280              280
Delis                            285    285             285              285
Food Delivery Services            25     25              25               25

In [23]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(['Deli / Bodega', 'Delis'],'Deli'))

In [24]:
#Bar
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Bar')].groupby(['Venue Category']).count()

                        Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Bar                              213    213             213              213
Barbeque                          42     42              42               42
Barbers                            1      1               1                1
Bars                             159    159             159              159
Beach Bar                          1      1               1                1
Beer Bar                          26     26              26               26
Cigar Bars                         1      1               1                1
Cocktail Bar                      99     99              99               99
Cocktail Bars                     90     90              90               90
Dive Bar                          14     14              14               14
Dive Bars                         14     14              14               14
Gay Bar                            3      3               3                3
Gay Bars                           1      1               1                1
Hookah Bar                        16     16              16               16
Hookah Bars                       23     23              23               23
Hotel Bar                         18     18              18               18
Juice Bar                         58     58              58               58
Juice Bars & Smoothies            45     45              43               43
Karaoke Bar                       15     15              15               15
Piano Bar                          2      2               2                2
Rooftop Bar                        1      1               1                1
Sake Bar                           4      4               4                4
Salon / Barbershop                44     44              44               44
Sports Bar                        14     14              14               14
Sports Bars                       44     44              44               44
Sushi Bars                       119    119             119              119
Tapas Bars                        11     11              11               11
Tiki Bar                           5      5               5                5
Tiki Bars                          2      2               2                2
Whiskey Bars                       2      2               2                2
Whisky Bar                         5      5               5                5
Wine Bar                          63     63              63               63
Wine Bars                         47     47              47               47

In [25]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Bars', 'Beer Bar', 'Cocktail Bar', 'Cocktail Bars','Dive Bar', 'Dive Bars', 'Hookah Bar', 'Hookah Bars',
    'Sake Bar', 'Tiki Bar', 'Tiki Bars', 'Whiskey Bars', 'Whisky Bar'],'Bar'))

In [26]:
#Wine
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Wine')].groupby(['Venue Category']).count()

                      Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Beer, Wine & Spirits             6      6               6                6
Wine Bar                        63     63              63               63
Wine Bars                       47     47              47               47
Wine Shop                       90     90              90               90

In [27]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Beer, Wine & Spirits', 'Wine Bar', 'Wine Bars', 'Wine Shop'],'Wine Place'))

In [28]:
#Sandwich
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Sandw')].groupby(['Venue Category']).count()

                Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Sandwich Place           179    179             179              179
Sandwiches               164    164             164              164

In [29]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Sandwich Place', 'Sandwiches'],'Sandwich Restaurant'))

In [30]:
#Cafe
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Caf')].groupby(['Venue Category']).count()

                      Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Cafes                          111    111             111              111
Cafeteria                        8      8               8                8
CafÃ©                           174    174             174              174
College Cafeteria                1      1               1                1
Gaming Cafe                      3      3               3                3
Hong Kong Style Cafe             2      2               2                2
Pet CafÃ©                         3      3               3                3
Themed Cafes                     3      3               3                3

In [31]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Cafes', 'Cafeteria', 'CafÃ©', 'College Cafeteria','Hong Kong Style Cafe', 'Pet CafÃ©', 'Themed Cafes'],'Cafe Restaurant'))

In [32]:
#American Restaurants

In [33]:
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Amer')].groupby(['Venue Category']).count()

,Neighborhood,Venue,Venue Latitude,Venue Longitude
Venue Category,,,,
American (New),186,186,186,186
American (Traditional),145,145,145,145
American Restaurant,162,162,162,162
Latin American,103,103,103,103
Latin American Restaurant,84,84,84,84
New American Restaurant,38,38,38,38
South American Restaurant,21,21,21,21

In [34]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['American (New)', 'American (Traditional)', 'New American Restaurant'],'American Restaurant'))

In [35]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Latin American', 'South American Restaurant'],'Latin American Restaurant'))

In [36]:
#Ice Cream
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Ice')].groupby(['Venue Category']).count()

,Neighborhood,Venue,Venue Latitude,Venue Longitude
Venue Category,,,,
Ice Cream & Frozen Yogurt,151,151,151,151
Ice Cream Shop,128,128,128,128

In [37]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Ice Cream & Frozen Yogurt', 'Ice Cream Shop'],'Ice Cream Restaurant'))

In [38]:
#Sushi
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Sushi')].groupby(['Venue Category']).count()

                  Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Sushi Bars                 119    119             119              119
Sushi Restaurant           111    111             111              111

In [39]:
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Japan')].groupby(['Venue Category']).count()

,Neighborhood,Venue,Venue Latitude,Venue Longitude
Venue Category,,,,
Japanese,118,118,118,118
Japanese Curry,4,4,4,4
Japanese Curry Restaurant,3,3,3,3
Japanese Restaurant,91,91,91,91

In [40]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Sushi Bars', 'Sushi Restaurant','Japanese', 'Japanese Curry', 'Japanese Curry Restaurant'],
    'Japanese Restaurant'))

In [41]:
#Gym
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Gym')].groupby(['Venue Category']).count()

                      Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Boxing Gym                      15     15              15               15
Climbing Gym                     4      4               4                4
Gym                            111    111             111              111
Gym / Fitness Center           122    122             122              122
Gym Pool                         1      1               1                1
Gymnastics Gym                   3      3               3                3
Outdoor Gym                      1      1               1                1

In [42]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Boxing Gym', 'Climbing Gym','Gym / Fitness Center', 'Gym Pool', 'Gymnastics Gym', 'Outdoor Gym'],
    'Gym'))

In [43]:
#Supermarket
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Gro')].groupby(['Venue Category']).count()

                 Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Grocery                    57     57              57               57
Grocery Store             183    183             183              183
Organic Grocery             7      7               7                7

In [44]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Grocery', 'Organic Grocery'],
    'Grocery Store'))

In [45]:
#Donuts
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Donut')].groupby(['Venue Category']).count()

                Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Donut Shop               157    157             157              157
Donuts                   104    104             104              104

In [46]:
venues_no_dups=venues_no_dups.replace('Donuts', 'Donut Shop')

In [47]:
#Bookstore
venues_no_dups[venues_no_dups['Venue Category'].str.contains('store')].groupby(['Venue Category']).count()

                   Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Bookstore                    49     49              49               49
Bookstores                    5      5               5                5
College Bookstore             1      1               1                1
Drugstore                     1      1               1                1
Used Bookstore                3      3               3                3

In [48]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Bookstores', 'College Bookstore','Used Bookstore'],
    'Bookstore'))

In [49]:
#Fastfood
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Fast')].groupby(['Venue Category']).count()

                      Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Fast Food                      188    188             188              188
Fast Food Restaurant            88     88              88               88

In [50]:
venues_no_dups=venues_no_dups.replace('Fast Food','Fast Food Restaurant')

In [51]:
#Diner
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Diner')].groupby(['Venue Category']).count()

                Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Diner                    104    104             104              104
Diners                    64     64              64               64

In [52]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(['Diner', 'Diners'], 'Diner Restaurant'))

In [53]:
#Dessert
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Dess')].groupby(['Venue Category']).count()

                Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Dessert Shop              67     67              67               67
Desserts                 154    154             154              154

In [54]:
venues_no_dups=venues_no_dups.replace('Desserts','Dessert Shop')

In [55]:
#Juice
venues_no_dups[venues_no_dups['Venue Category'].str.contains('uic')].groupby(['Venue Category']).count()

                        Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Juice Bar                         58     58              58               58
Juice Bars & Smoothies            45     45              43               43

In [56]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(['Juice Bar', 'Juice Bars & Smoothies'], 'Juice Restaurant'))

In [57]:
#Parks
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Park')].groupby(['Venue Category']).count()

,Neighborhood,Venue,Venue Latitude,Venue Longitude
Venue Category,,,,
Amusement Parks,2,2,2,2
Dog Parks,19,19,19,19
Park,188,188,188,188
Parks,123,123,123,123
Skate Park,4,4,4,4
Skate Parks,2,2,2,2
State / Provincial Park,1,1,1,1
Theme Park,2,2,2,2
Theme Park Ride / Attraction,5,5,5,5

In [58]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Parks', 'State / Provincial Park'], 
    'Park'))

In [59]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Amusement Parks', 'Theme Park', 'Theme Park Ride / Attraction'], 
    'Amusement Park'))

In [60]:
venues_no_dups=venues_no_dups.replace('Skate Parks', 'Skate Park')

In [61]:
#Bus
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Bus')].groupby(['Venue Category']).count()

                  Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Bus Line                     5      5               5                5
Bus Station                 82     82              82               82
Bus Stop                    71     71              71               71
Business Service             3      3               3                3

In [62]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Bus Line', 'Bus Station'],'Bus Stop'))

In [63]:
#Mall
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Mall')].groupby(['Venue Category']).count()

                Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Outlet Mall                1      1               1                1
Shopping Mall             17     17              17               17

In [64]:
venues_no_dups=venues_no_dups.replace('Outlet Mall', 'Shopping Mall')

In [65]:
#Mexican
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Mex')].groupby(['Venue Category']).count()

                     Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Mexican                       329    329             329              329
Mexican Restaurant            176    176             176              176
New Mexican Cuisine             4      4               4                4
Tex-Mex                        14     14              14               14
Tex-Mex Restaurant              1      1               1                1

In [66]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Mexican', 'New Mexican Cuisine'],'Mexican Restaurant'))

In [67]:
#Indian
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Ind')].groupby(['Venue Category']).count()

                         Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Indian                            188    188             188              188
Indian Restaurant                  68     68              68               68
Indie Movie Theater                11     11              11               11
Indie Theater                       8      8               8                8
Indonesian                          1      1               1                1
Indonesian Restaurant               1      1               1                1
Indoor Play Area                    1      1               1                1
North Indian Restaurant             3      3               3                3
South Indian Restaurant             2      2               2                2

In [68]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Indian', 'North Indian Restauran', 'South Indian Restaurant'],'Indian Restaurant'))

In [69]:
#Burger
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Burg')].groupby(['Venue Category']).count()

                Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Burger Joint              88     88              88               88
Burgers                  148    148             148              148

In [70]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Burger Joint', 'Burgers'],'Burger Restaurant'))

In [71]:
#Korean
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Kore')].groupby(['Venue Category']).count()

                       Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Korean                           94     94              94               94
Korean BBQ Restaurant             1      1               1                1
Korean Restaurant                77     77              77               77

In [72]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Korean', 'Korean BBQ Restaurant'],'Korean Restaurant'))

In [73]:
#Seafood
venues_no_dups[venues_no_dups['Venue Category'].str.contains('eafoo')].groupby(['Venue Category']).count()

                    Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Seafood                      145    145             145              145
Seafood Markets                6      6               6                6
Seafood Restaurant            77     77              77               77

In [74]:
venues_no_dups=venues_no_dups.replace('Seafood', 'Seafood Restaurant')

In [75]:
#Seafood
venues_no_dups[venues_no_dups['Venue Category'].str.contains('agel')].groupby(['Venue Category']).count()

                Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Bagel Shop               118    118             118              118
Bagels                    69     69              69               69

In [76]:
venues_no_dups=venues_no_dups.replace('Bagels', 'Bagel Shop')

In [77]:
#Restaurant
venues_no_dups[venues_no_dups['Venue Category'].str.contains('estau')].groupby(['Venue Category']).count()

,Neighborhood,Venue,Venue Latitude,Venue Longitude
Venue Category,,,,
Afghan Restaurant,3,3,3,3
African Restaurant,4,4,4,4
American Restaurant,531,531,531,531
Arepa Restaurant,8,8,8,8
Argentinian Restaurant,10,10,10,10
...,...,...,...,...
Varenyky restaurant,1,1,1,1
Vegetarian / Vegan Restaurant,39,39,39,39
Venezuelan Restaurant,1,1,1,1
Vietnamese Restaurant,40,40,40,40
Yemeni Restaurant,1,1,1,1

In [78]:
venues_no_dups=venues_no_dups.replace('Restaurants', 'Restaurant')

In [79]:
#Thai
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Thai')].groupby(['Venue Category']).count()

                 Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Thai                      107    107             107              107
Thai Restaurant            89     89              89               89

In [80]:
venues_no_dups=venues_no_dups.replace('Thai', 'Thai Restaurant')

In [81]:
#Spanish
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Span')].groupby(['Venue Category']).count()

                    Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Spanish                       80     80              78               78
Spanish Restaurant            62     62              62               62

In [82]:
#Chicken
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Chick')].groupby(['Venue Category']).count()

,Neighborhood,Venue,Venue Latitude,Venue Longitude
Venue Category,,,,
Chicken Shop,21,21,21,21
Chicken Wings,76,76,76,76
Fried Chicken Joint,76,76,76,76
Peruvian Roast Chicken Joint,1,1,1,1

In [83]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Chicken Wings', 'Fried Chicken Joint'],'Chicken Restaurant'))

In [84]:
#Caribbian
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Carib')].groupby(['Venue Category']).count()

                      Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Caribbean                      163    163             163              163
Caribbean Restaurant            87     87              87               87

In [85]:
venues_no_dups=venues_no_dups.replace('Caribbean', 'Caribbean Restaurant')

In [86]:
#Food Truck
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Truck')].groupby(['Venue Category']).count()

                Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Food Truck                55     55              55               55
Food Trucks              356    356             356              356

In [87]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Food Truck', 'Food Trucks'],'Food Truck Restaurant'))

In [88]:
#Mediterrean
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Medit')].groupby(['Venue Category']).count()

                          Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Mediterranean                       57     57              57               57
Mediterranean Restaurant            48     48              48               48

In [89]:
venues_no_dups=venues_no_dups.replace('Mediterranean', 'Mediterranean Restaurant')

In [90]:
#Breakfast
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Break')].groupby(['Venue Category']).count()

                    Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Breakfast & Brunch            89     89              89               89
Breakfast Spot                43     43              43               43

In [91]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Breakfast & Brunch', 'Breakfast Spot'],'Breakfast Restaurant'))

In [92]:
#Steakhouse
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Steak')].groupby(['Venue Category']).count()

                Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Steakhouse                41     41              41               41
Steakhouses               37     37              37               37

In [93]:
venues_no_dups=venues_no_dups.replace(dict.fromkeys(
    ['Steakhouse', 'Steakhouses'],'Steakhouse Restaurant'))

In [94]:
#Ramen
venues_no_dups[venues_no_dups['Venue Category'].str.contains('Ramen')].groupby(['Venue Category']).count()

                  Neighborhood  Venue  Venue Latitude  Venue Longitude
Venue Category
Ramen                       40     40              40               40
Ramen Restaurant            29     29              29               29

In [95]:
venues_no_dups=venues_no_dups.replace('Ramen', 'Ramen Restaurant')

In [96]:
#Lets count number of restaurants for each neighborhood
restaurants=venues_no_dups[venues_no_dups['Venue Category'].str.contains('Restaurant')].groupby(['Neighborhood'], as_index=False).count()

In [97]:
restaurants['Number_of_Restaurants']=restaurants['Venue']

In [98]:
number_of_restaurants=restaurants.drop(['Venue', 'Venue Latitude', 'Venue Longitude', 'Venue Category'], axis=1)

In [99]:
#This is the number of restaurants for each nbhood, we will put it as feature to intial DataFrame
number_of_restaurants

      Neighborhood  Number_of_Restaurants
0         Allerton                     36
1         Annadale                      6
2    Arden Heights                      2
3        Arlington                      1
4         Arrochar                     10
..             ...                    ...
286      Woodhaven                     39
287       Woodlawn                     14
288        Woodrow                      8
289       Woodside                     65
290      Yorkville                     76

[291 rows x 2 columns]

In [100]:
#Put nbhoods with restaurants into the set to check which nbhoods do not have any restaurants at all
nbhoods_with_restaurants=set(restaurants['Neighborhood'])

In [101]:
#Find the top category for each nbhood

FIND THE TOP RESTAURANT FOR EACH NEIGHBORHOOD

In [102]:
#Find the top restaurant category for each nbhood
venues_no_dups

,Neighborhood,Venue,Venue Latitude,Venue Longitude,Venue Category
0,Marble Hill,Bikram Yoga,40.876844,-73.906204,Yoga Studio
1,Marble Hill,Arturo's,40.874412,-73.910271,Pizza Restaurant
2,Marble Hill,Tibbett Diner,40.880404,-73.908937,Diner Restaurant
3,Marble Hill,Dunkin',40.877136,-73.906666,Donut Shop
4,Marble Hill,Starbucks,40.877531,-73.905582,Coffee Restaurant
...,...,...,...,...,...
19126,Elm Park,New Ranchito Deli,40.631000,-74.147110,Food Delivery Services
19127,Elm Park,The New Dinette,40.636612,-74.133980,Restaurant
19128,Elm Park,Baskin-Robbins,40.626640,-74.135071,Ice Cream Restaurant
19129,Elm Park,Sin Fronters Deli,40.632770,-74.134330,Deli
19130,Elm Park,Exotic,40.626718,-74.131770,Vape Shops

In [103]:
#Take venues with word Restaurant
grouped_cat=venues_no_dups.loc[venues_no_dups['Venue Category'].str.contains('Restaurant')].groupby(['Neighborhood', 'Venue Category'], as_index=False).count().sort_values(by=['Neighborhood','Venue'], ascending=False)

In [104]:
#Group by nbhood and select only category with maximum frequency
grouped_cat=grouped_cat[['Neighborhood','Venue Category','Venue']].groupby(['Neighborhood']).max().sort_values(by=['Venue'], ascending=False)

In [147]:
grouped_cat

                  Neighborhood          Top Restaurant Category
166                   Allerton              Sandwich Restaurant
233                   Annadale                       Restaurant
255              Arden Heights                 Pizza Restaurant
253                  Arlington              American Restaurant
209                   Arrochar              Sandwich Restaurant
108                    Arverne              Sandwich Restaurant
153                    Astoria    Vegetarian / Vegan Restaurant
266            Astoria Heights                 Pizza Restaurant
205                 Auburndale                  Thai Restaurant
99                  Bath Beach               Turkish Restaurant
24           Battery Park City            Steakhouse Restaurant
54                   Bay Ridge            Vietnamese Restaurant
279                Bay Terrace              Japanese Restaurant
204              Bay Terrace Q            Steakhouse Restaurant
225             Bay Terrace SI                  Thai Restaurant
217                 Baychester               Spanish Restaurant
136                    Bayside            Vietnamese Restaurant
100               Bedford Park               Spanish Restaurant
41          Bedford Stuyvesant               Seafood Restaurant
232                 Beechhurst                       Restaurant
230                   Bellaire               Italian Restaurant
113               Belle Harbor                       Restaurant
117                  Bellerose               Seafood Restaurant
4                      Belmont               Spanish Restaurant
10                 Bensonhurst           Shabu-Shabu Restaurant
144                 Blissville                  Thai Restaurant
249                 Bloomfield                Burger Restaurant
48                 Boerum Hill                  Thai Restaurant
172               Borough Park               Seafood Restaurant
119                  Briarwood              Sandwich Restaurant
71              Brighton Beach               Russian Restaurant
250              Broad Channel                 Pizza Restaurant
173          Broadway Junction               Seafood Restaurant
145                  Bronxdale               Spanish Restaurant
60            Brooklyn Heights            Vietnamese Restaurant
93                 Brownsville               Spanish Restaurant
210                 Bulls Head                  Thai Restaurant
42                    Bushwick    Vegetarian / Vegan Restaurant
211            Cambria Heights                       Restaurant
252                   Canarsie                  Thai Restaurant
27               Carnegie Hill            Vietnamese Restaurant
7              Carroll Gardens                  Thai Restaurant
248                Castle Hill                 Pizza Restaurant
199          Castleton Corners              Sandwich Restaurant
143             Central Harlem  Southern / Soul Food Restaurant
241                 Charleston                 Pizza Restaurant
76                   Chelsea M                  Thai Restaurant
256                 Chelsea SI            Steakhouse Restaurant
13                   Chinatown            Vietnamese Restaurant
186                City Island               Spanish Restaurant
131                  City Line                  Thai Restaurant
40                Civic Center    Vegetarian / Vegan Restaurant
168          Claremont Village            Steakhouse Restaurant
251               Clason Point        Latin American Restaurant
222                    Clifton                       Restaurant
21                     Clinton                  Thai Restaurant
77                Clinton Hill            Vietnamese Restaurant
245                 Co-op City                       Restaurant
46                 Cobble Hill                Yemeni Restaurant
123              College Point            Steakhouse Restaurant
246                    Concord              Peruvian Restaurant
39                   Concourse               Spanish Restaurant
74           Concourse Village              Sandwich Restaurant
182               Coney Island               Seafood Restaurant
121                     Corona              Sandwich Restaurant
224               Country Club              Sandwich Restaurant
69               Crown Heights                 Pizza Restaurant
125              Cypress Hills               Spanish Restaurant
65                 Ditmas Park               Tibetan Restaurant
202               Dongan Hills              Sandwich Restaurant
38                  Douglaston                  Thai Restaurant
55                    Downtown                  Thai Restaurant
37                       Dumbo            Vietnamese Restaurant
58               Dyker Heights                  Thai Restaurant
169              East Elmhurst               Seafood Restaurant
218              East Flatbush            Food Truck Restaurant
22                 East Harlem                  Thai Restaurant
223              East New York               Spanish Restaurant
167               East Tremont              Sandwich Restaurant
102               East Village            Vietnamese Restaurant
91           East Williamsburg    Vegetarian / Vegan Restaurant
194                Eastchester               Seafood Restaurant
286                   Edenwald              Sandwich Restaurant
284                   Edgemere               Seafood Restaurant
175             Edgewater Park                 Pizza Restaurant
282                Egbertville               Italian Restaurant
129                   Elm Park               Seafood Restaurant
135                   Elmhurst            Vietnamese Restaurant
187                Eltingville              Sandwich Restaurant
5                      Erasmus               Seafood Restaurant
124               Far Rockaway  Southern / Soul Food Restaurant
280                  Fieldston               Mexican Restaurant
15          Financial District            Steakhouse Restaurant
57                    Flatbush               Seafood Restaurant
14                    Flatiron    Vegetarian / Vegan Restaurant
243                  Flatlands             Fast Food Restaurant
171                Floral Park              Sandwich Restaurant
64                    Flushing              Szechuan Restaurant
126                    Fordham               Spanish Restaurant
197               Forest Hills                  Thai Restaurant
180       Forest Hills Gardens              Sandwich Restaurant
120                Fort Greene            Vietnamese Restaurant
18               Fort Hamilton                  Thai Restaurant
277                  Fox Hills              Sandwich Restaurant
68               Fresh Meadows    Vegetarian / Vegan Restaurant
84                Fulton Ferry            Vietnamese Restaurant
244                 Georgetown               Seafood Restaurant
240            Gerritsen Beach               Seafood Restaurant
179                  Glen Oaks              Sandwich Restaurant
88                    Glendale               Seafood Restaurant
87                     Gowanus                  Thai Restaurant
85                    Gramercy                  Thai Restaurant
90                  Grant City                 Pizza Restaurant
275                   Grasmere    Vegetarian / Vegan Restaurant
178                  Gravesend                       Restaurant
239                Great Kills               Spanish Restaurant
20                  Greenpoint            Vietnamese Restaurant
272                 Greenridge                 Pizza Restaurant
6            Greenwich Village            Vietnamese Restaurant
66            Hamilton Heights                  Thai Restaurant
31                     Hammels               Seafood Restaurant
271          Heartland Village                       Restaurant
81                High  Bridge               Seafood Restaurant
237              Highland Park                 Pizza Restaurant
188                  Hillcrest              Sandwich Restaurant
107                     Hollis               Seafood Restaurant
147                 Holliswood               Seafood Restaurant
82                   Homecrest            Vietnamese Restaurant
56                Howard Beach                 Tapas Restaurant
59                Hudson Yards                  Thai Restaurant
270                   Huguenot              Sandwich Restaurant
86               Hunters Point            Vietnamese Restaurant
269                Hunts Point               Spanish Restaurant
43                      Inwood            Steakhouse Restaurant
11             Jackson Heights                  Thai Restaurant
174             Jamaica Center                  Thai Restaurant
212            Jamaica Estates              Sandwich Restaurant
104              Jamaica Hills                  Thai Restaurant
52                  Kensington                  Thai Restaurant
103                Kew Gardens                  Thai Restaurant
234          Kew Gardens Hills              Sandwich Restaurant
30                 Kingsbridge    Vegetarian / Vegan Restaurant
29         Kingsbridge Heights            Vietnamese Restaurant
148                  Laurelton               Seafood Restaurant
154                Lefrak City            Steakhouse Restaurant
17                  Lenox Hill               Turkish Restaurant
265            Lighthouse Hill               Italian Restaurant
28              Lincoln Square                  Thai Restaurant
264                 Lindenwood                 Pizza Restaurant
33                Little Italy            Vietnamese Restaurant
25                 Little Neck            Vietnamese Restaurant
35            Long Island City                  Thai Restaurant
109                   Longwood              Sandwich Restaurant
170            Lower East Side            Vietnamese Restaurant
290                    Madison                       Restaurant
263                      Malba    Vegetarian / Vegan Restaurant
231            Manhattan Beach              Sandwich Restaurant
26           Manhattan Terrace            Steakhouse Restaurant
141           Manhattan Valley            Vietnamese Restaurant
114             Manhattanville               Spanish Restaurant
262              Manor Heights                 Pizza Restaurant
115                Marble Hill            Steakhouse Restaurant
261                Marine Park                 Pizza Restaurant
283           Mariner's Harbor               Italian Restaurant
94                     Maspeth               Seafood Restaurant
19                     Melrose               Seafood Restaurant
89              Middle Village               Seafood Restaurant
258              Midland Beach               Russian Restaurant
73                     Midtown            Vietnamese Restaurant
1                Midtown South    Vegetarian / Vegan Restaurant
78                     Midwood               Seafood Restaurant
142                 Mill Basin              Sandwich Restaurant
36         Morningside Heights                  Thai Restaurant
162             Morris Heights               Spanish Restaurant
98                 Morris Park               Seafood Restaurant
111                 Morrisania            Steakhouse Restaurant
105                 Mott Haven               Spanish Restaurant
140                 Mount Eden               Spanish Restaurant
106                 Mount Hope               Spanish Restaurant
0                  Murray Hill               Seafood Restaurant
151              Murray Hill M            Vietnamese Restaurant
2                Murray Hill Q                 Pizza Restaurant
116                   Neponsit              Sandwich Restaurant
267               New Brighton               Mexican Restaurant
215                   New Dorp            Vietnamese Restaurant
235             New Dorp Beach                       Restaurant
236                   New Lots                 Pizza Restaurant
268            New Springville              Sandwich Restaurant
92                        Noho            Vietnamese Restaurant
183               North Corona                  Thai Restaurant
193            North Riverdale              Sandwich Restaurant
12                  North Side    Vegetarian / Vegan Restaurant
110                    Norwood               Spanish Restaurant
45             Oakland Gardens            Vietnamese Restaurant
149                 Ocean Hill  Southern / Soul Food Restaurant
101              Ocean Parkway            Steakhouse Restaurant
177                   Old Town                       Restaurant
164                  Olinville              Sandwich Restaurant
134                 Ozone Park               Spanish Restaurant
273            Paerdegat Basin                 Asian Restaurant
274                  Park Hill                Coffee Restaurant
83                  Park Slope            Vietnamese Restaurant
133                Parkchester            Steakhouse Restaurant
216                 Pelham Bay                  Thai Restaurant
276             Pelham Gardens               Spanish Restaurant
176             Pelham Parkway              Sandwich Restaurant
208            Pleasant Plains                 Pizza Restaurant
200                    Pomonok              Sandwich Restaurant
229                Port Morris                       Restaurant
159              Port Richmond                  Thai Restaurant
242               Prince's Bay                 Pizza Restaurant
72            Prospect Heights            Vietnamese Restaurant
34   Prospect Lefferts Gardens               Spanish Restaurant
61         Prospect Park South                  Thai Restaurant
127             Queens Village              Sandwich Restaurant
53             Queensboro Hill             Taiwanese Restaurant
79                Queensbridge               Spanish Restaurant
278              Randall Manor                 Pizza Restaurant
165                 Ravenswood                  Thai Restaurant
185                   Red Hook                  Thai Restaurant
155                  Rego Park                  Thai Restaurant
203             Remsen Village              Sandwich Restaurant
146              Richmond Hill               Spanish Restaurant
281              Richmond Town               Italian Restaurant
228            Richmond Valley              Sandwich Restaurant
122                  Ridgewood    Vegetarian / Vegan Restaurant
189                  Riverdale               Seafood Restaurant
220                   Rochdale  Southern / Soul Food Restaurant
51              Rockaway Beach    Vegetarian / Vegan Restaurant
44               Rockaway Park               Seafood Restaurant
152           Roosevelt Island               Seafood Restaurant
184                   Rosedale              Sandwich Restaurant
198                  Rossville                 Pizza Restaurant
285                    Roxbury             Fast Food Restaurant
62                       Rugby               Seafood Restaurant
287               Sandy Ground            Food Truck Restaurant
181              Schuylerville              Sandwich Restaurant
288                   Sea Gate              American Restaurant
150             Sheepshead Bay               Turkish Restaurant
207                Shore Acres                       Restaurant
289                Silver Lake                Burger Restaurant
9                         Soho    Vegetarian / Vegan Restaurant
213                  Soundview        Latin American Restaurant
226              South Jamaica    Vegetarian / Vegan Restaurant
63            South Ozone Park              Sandwich Restaurant
23                  South Side            Vietnamese Restaurant
260        Springfield Gardens              Sandwich Restaurant
219             Spuyten Duyvil                  Thai Restaurant
191                 St. Albans               Seafood Restaurant
195                 St. George                 Tapas Restaurant
196                  Stapleton            Sri Lankan Restaurant
259              Starrett City                 Pizza Restaurant
160                   Steinway                  Thai Restaurant
137            Stuyvesant Town                  Thai Restaurant
201                  Sunnyside                 Pizza Restaurant
128          Sunnyside Gardens               Turkish Restaurant
163                Sunnyside Q               Seafood Restaurant
227               Sunnyside SI              Sandwich Restaurant
139                Sunset Park                  Thai Restaurant
75                Sutton Place    Vegetarian / Vegan Restaurant
221                Throgs Neck                 Pizza Restaurant
138              Tompkinsville               Spanish Restaurant
254                Tottenville               Mexican Restaurant
16                     Tribeca    Vegetarian / Vegan Restaurant
96                  Tudor City            Vietnamese Restaurant
47                  Turtle Bay               Turkish Restaurant
130                  Unionport               Seafood Restaurant
132         University Heights              Sandwich Restaurant
50             Upper East Side    Vegetarian / Vegan Restaurant
32             Upper West Side            Vietnamese Restaurant
158                     Utopia               Seafood Restaurant
157                   Van Nest               Seafood Restaurant
118               Vinegar Hill              Sandwich Restaurant
257                  Wakefield              Sandwich Restaurant
95          Washington Heights                  Thai Restaurant
70                  Weeksville            Steakhouse Restaurant
238              West Brighton              Sandwich Restaurant
214                 West Farms              Sandwich Restaurant
3                 West Village               Seafood Restaurant
49          Westchester Square               Spanish Restaurant
206                Westerleigh                  Thai Restaurant
67                  Whitestone               Seafood Restaurant
192             Williamsbridge               Seafood Restaurant
156               Williamsburg                  Thai Restaurant
161            Windsor Terrace                  Thai Restaurant
80                     Wingate               Seafood Restaurant
112                  Woodhaven                  Thai Restaurant
190                   Woodlawn                 Pizza Restaurant
247                    Woodrow                 Pizza Restaurant
97                    Woodside               Tibetan Restaurant
8                    Yorkville            Vietnamese Restaurant

In [105]:
grouped_cat=grouped_cat.drop(columns=['Venue'])

In [106]:
grouped_cat=pd.DataFrame(grouped_cat.rename(columns={'Venue Category': 'Top Restaurant Category'}))

In [107]:
grouped_cat=grouped_cat.reset_index()

In [108]:
grouped_cat=grouped_cat.sort_values(by=['Neighborhood'])

In [109]:
#Dataframe for Top restaurant categories
grouped_cat

      Neighborhood Top Restaurant Category
166       Allerton     Sandwich Restaurant
233       Annadale              Restaurant
255  Arden Heights        Pizza Restaurant
253      Arlington     American Restaurant
209       Arrochar     Sandwich Restaurant
..             ...                     ...
112      Woodhaven         Thai Restaurant
190       Woodlawn        Pizza Restaurant
247        Woodrow        Pizza Restaurant
97        Woodside      Tibetan Restaurant
8        Yorkville   Vietnamese Restaurant

[291 rows x 2 columns]

In [110]:
categories=venues_no_dups.groupby(['Venue Category'], as_index=False).count()

In [111]:
categories.sort_values('Neighborhood', ascending=False).head(100)

          Venue Category  Neighborhood  Venue  Venue Latitude  Venue Longitude
414     Pizza Restaurant           961    961             961              961
120    Coffee Restaurant           774    774             774              774
112   Chinese Restaurant           759    759             759              759
41                   Bar           672    672             672              672
38                Bakery           634    634             634              634
..                   ...           ...    ...             ...              ...
159     Department Store            28     28              28               28
498  Sporting Goods Shop            28     28              28               28
206          Flower Shop            28     28              28               28
509       Street Vendors            28     28              28               28
458          Salad Place            28     28              28               28

[100 rows x 5 columns]

In [112]:
#categories['Venue Category'].tolist()

In [113]:
categories.loc[categories['Venue Category']=='School'] #We have schools only for 5 nbhoods

    Venue Category  Neighborhood  Venue  Venue Latitude  Venue Longitude
465         School             5      5               5                5

In [114]:
categories.loc[categories['Venue Category']=='Bank'] #141 nbhoods have banks

   Venue Category  Neighborhood  Venue  Venue Latitude  Venue Longitude
40           Bank           141    141             141              141

In [115]:
categories.loc[categories['Venue Category']=='Pharmacy'] #173 nbhoods have Pharmacy

    Venue Category  Neighborhood  Venue  Venue Latitude  Venue Longitude
406       Pharmacy           173    173             173              173

In [116]:
#Count number of venues for each neighborhood
number_of_venues=venues_no_dups.groupby(by='Neighborhood', as_index=False).count()

In [117]:
number_of_venues['Number_of_venues']=number_of_venues['Venue']

In [118]:
number_of_venues=number_of_venues.drop(columns=['Venue', 'Venue Latitude', 'Venue Longitude', 'Venue Category'])

In [119]:
number_of_venues['Number_of_venues'].sum()

19027

In [120]:
nbhoods_new=pd.read_csv('nbhoods_new.csv')

In [121]:
nbhoods_new=nbhoods_new.merge(number_of_venues, on='Neighborhood', how='left')

In [122]:
pd.set_option('display.max_rows', 500)
nbhoods_new=nbhoods_new.drop(columns=['LL', 'Bbox'])

In [123]:
nbhoods_new

,Borough,Neighborhood,Latitude,Longitude,Number_of_venues
0,Bronx,Wakefield,40.894705,-73.847201,11.0
1,Bronx,Co-op City,40.874294,-73.829939,16.0
2,Bronx,Eastchester,40.887556,-73.827806,26.0
3,Bronx,Fieldston,40.895437,-73.905643,13.0
4,Bronx,Riverdale,40.890834,-73.912585,39.0
5,Bronx,Kingsbridge,40.881687,-73.902818,119.0
6,Manhattan,Marble Hill,40.876551,-73.910660,71.0
7,Bronx,Woodlawn,40.898273,-73.867315,48.0
8,Bronx,Norwood,40.877224,-73.879391,78.0
9,Bronx,Williamsbridge,40.881039,-73.857446,38.0
10,Bronx,Baychester,40.866858,-73.835798,28.0
11,Bronx,Pelham Parkway,40.857413,-73.854756,37.0
12,Bronx,City Island,40.847247,-73.786488,46.0
13,Bronx,Bedford Park,40.870185,-73.885512,86.0
14,Bronx,University Heights,40.855727,-73.910416,71.0
15,Bronx,Morris Heights,40.847898,-73.919672,56.0
16,Bronx,Fordham,40.860997,-73.896427,136.0
17,Bronx,East Tremont,40.842696,-73.887356,35.0
18,Bronx,West Farms,40.839475,-73.877745,40.0
19,Bronx,High Bridge,40.836623,-73.926102,74.0
20,Bronx,Melrose,40.819754,-73.909422,75.0
21,Bronx,Mott Haven,40.806239,-73.916100,58.0
22,Bronx,Port Morris,40.801664,-73.913221,16.0
23,Bronx,Longwood,40.815099,-73.895788,54.0
24,Bronx,Hunts Point,40.809730,-73.883315,13.0
25,Bronx,Morrisania,40.823592,-73.901506,70.0
26,Bronx,Soundview,40.821012,-73.865746,17.0
27,Bronx,Clason Point,40.806551,-73.854144,11.0
28,Bronx,Throgs Neck,40.815109,-73.816350,11.0
29,Bronx,Country Club,40.844246,-73.824099,15.0
30,Bronx,Parkchester,40.837938,-73.856003,83.0
31,Bronx,Westchester Square,40.840619,-73.842194,85.0
32,Bronx,Van Nest,40.843608,-73.866299,60.0
33,Bronx,Morris Park,40.847549,-73.850402,74.0
34,Bronx,Belmont,40.857277,-73.888452,149.0
35,Bronx,Spuyten Duyvil,40.881395,-73.917190,25.0
36,Bronx,North Riverdale,40.908543,-73.904531,27.0
37,Bronx,Pelham Bay,40.850641,-73.832074,54.0
38,Bronx,Schuylerville,40.826580,-73.826203,37.0
39,Bronx,Edgewater Park,40.821986,-73.813885,20.0
40,Bronx,Castle Hill,40.819014,-73.848027,7.0
41,Bronx,Olinville,40.871371,-73.863324,51.0
42,Bronx,Pelham Gardens,40.862966,-73.841612,18.0
43,Bronx,Concourse,40.834284,-73.915589,76.0
44,Bronx,Unionport,40.829774,-73.850535,71.0
45,Bronx,Edenwald,40.884561,-73.848083,4.0
46,Brooklyn,Bay Ridge,40.625801,-74.030621,127.0
47,Brooklyn,Bensonhurst,40.611009,-73.995180,82.0
48,Brooklyn,Sunset Park,40.645103,-74.010316,88.0
49,Brooklyn,Greenpoint,40.730201,-73.954241,150.0
50,Brooklyn,Gravesend,40.595260,-73.973471,53.0
51,Brooklyn,Brighton Beach,40.576825,-73.965094,83.0
52,Brooklyn,Sheepshead Bay,40.586890,-73.943186,76.0
53,Brooklyn,Manhattan Terrace,40.614433,-73.957438,74.0
54,Brooklyn,Flatbush,40.636326,-73.958401,71.0
55,Brooklyn,Crown Heights,40.670829,-73.943291,68.0
56,Brooklyn,East Flatbush,40.641718,-73.936103,19.0
57,Brooklyn,Kensington,40.642382,-73.980421,86.0
58,Brooklyn,Windsor Terrace,40.656946,-73.980073,77.0
59,Brooklyn,Prospect Heights,40.676822,-73.964859,132.0
60,Brooklyn,Brownsville,40.663950,-73.910235,56.0
61,Brooklyn,Williamsburg,40.707144,-73.958115,81.0
62,Brooklyn,Bushwick,40.698116,-73.925258,115.0
63,Brooklyn,Bedford Stuyvesant,40.687232,-73.941785,82.0
64,Brooklyn,Brooklyn Heights,40.695864,-73.993782,149.0
65,Brooklyn,Cobble Hill,40.687920,-73.998561,150.0
66,Brooklyn,Carroll Gardens,40.680540,-73.994654,150.0
67,Brooklyn,Red Hook,40.676253,-74.012759,61.0
68,Brooklyn,Gowanus,40.673931,-73.994441,116.0
69,Brooklyn,Fort Greene,40.688527,-73.972906,118.0
70,Brooklyn,Park Slope,40.672321,-73.977050,115.0
71,Brooklyn,Cypress Hills,40.682391,-73.876616,68.0
72,Brooklyn,East New York,40.669926,-73.880699,20.0
73,Brooklyn,Starrett City,40.647589,-73.879370,11.0
74,Brooklyn,Canarsie,40.635564,-73.902093,6.0
75,Brooklyn,Flatlands,40.630446,-73.929113,18.0
76,Brooklyn,Mill Island,40.606336,-73.908186,2.0
77,Brooklyn,Manhattan Beach,40.577914,-73.943537,19.0
78,Brooklyn,Coney Island,40.574293,-73.988683,53.0
79,Brooklyn,Bath Beach,40.599519,-73.998752,98.0
80,Brooklyn,Borough Park,40.633131,-73.990498,69.0
81,Brooklyn,Dyker Heights,40.619219,-74.019314,58.0
82,Brooklyn,Gerritsen Beach,40.590848,-73.930102,21.0
83,Brooklyn,Marine Park,40.609748,-73.931344,8.0
84,Brooklyn,Clinton Hill,40.693229,-73.967843,149.0
85,Brooklyn,Sea Gate,40.576375,-74.007873,6.0
86,Brooklyn,Downtown,40.690844,-73.983463,149.0
87,Brooklyn,Boerum Hill,40.685683,-73.983748,144.0
88,Brooklyn,Prospect Lefferts Gardens,40.658420,-73.954899,99.0
89,Brooklyn,Ocean Hill,40.678403,-73.913068,73.0
90,Brooklyn,City Line,40.678570,-73.867976,87.0
91,Brooklyn,Bergen Beach,40.615150,-73.898556,6.0
92,Brooklyn,Midwood,40.625596,-73.957595,61.0
93,Brooklyn,Prospect Park South,40.647009,-73.962613,103.0
94,Brooklyn,Georgetown,40.623845,-73.916075,27.0
95,Brooklyn,East Williamsburg,40.708492,-73.938858,116.0
96,Brooklyn,North Side,40.714823,-73.958809,149.0
97,Brooklyn,South Side,40.710861,-73.958001,149.0
98,Brooklyn,Ocean Parkway,40.613060,-73.968367,68.0
99,Brooklyn,Fort Hamilton,40.614768,-74.031979,107.0
100,Manhattan,Chinatown,40.715618,-73.994279,150.0
101,Manhattan,Washington Heights,40.851903,-73.936900,135.0
102,Manhattan,Inwood,40.867684,-73.921210,103.0
103,Manhattan,Hamilton Heights,40.823604,-73.949688,109.0
104,Manhattan,Manhattanville,40.816934,-73.957385,98.0
105,Manhattan,Central Harlem,40.815976,-73.943211,95.0
106,Manhattan,East Harlem,40.792249,-73.944182,93.0
107,Manhattan,Upper East Side,40.775639,-73.960508,147.0
108,Manhattan,Yorkville,40.775930,-73.947118,150.0
109,Manhattan,Lenox Hill,40.768113,-73.958860,149.0
110,Manhattan,Roosevelt Island,40.762160,-73.949168,79.0
111,Manhattan,Upper West Side,40.787658,-73.977059,150.0
112,Manhattan,Lincoln Square,40.773529,-73.985338,146.0
113,Manhattan,Clinton,40.759101,-73.996119,150.0
114,Manhattan,Midtown,40.754691,-73.981669,149.0
115,Manhattan,Murray Hill M,40.748303,-73.978332,100.0
116,Manhattan,Chelsea M,40.744035,-74.003116,150.0
117,Manhattan,Greenwich Village,40.726933,-73.999914,150.0
118,Manhattan,East Village,40.727847,-73.982226,150.0
119,Manhattan,Lower East Side,40.717807,-73.980890,97.0
120,Manhattan,Tribeca,40.721522,-74.010683,141.0
121,Manhattan,Little Italy,40.719324,-73.997305,150.0
122,Manhattan,Soho,40.722184,-74.000657,150.0
123,Manhattan,West Village,40.734434,-74.006180,150.0
124,Manhattan,Manhattan Valley,40.797307,-73.964286,99.0
125,Manhattan,Morningside Heights,40.808000,-73.963896,93.0
126,Manhattan,Gramercy,40.737210,-73.981376,148.0
127,Manhattan,Battery Park City,40.711932,-74.016869,141.0
128,Manhattan,Financial District,40.707107,-74.010665,148.0
129,Queens,Astoria,40.768509,-73.915654,150.0
130,Queens,Woodside,40.746349,-73.901842,132.0
131,Queens,Jackson Heights,40.751981,-73.882821,128.0
132,Queens,Elmhurst,40.744049,-73.881656,84.0
133,Queens,Howard Beach,40.654225,-73.838138,87.0
134,Queens,Corona,40.742382,-73.856825,70.0
135,Queens,Bay Terrace SI,40.725264,-73.844475,41.0
136,Queens,Kew Gardens,40.705179,-73.829819,103.0
137,Queens,Richmond Hill,40.697947,-73.831833,77.0
138,Queens,Flushing,40.764454,-73.831773,107.0
139,Queens,Long Island City,40.750217,-73.939202,123.0
140,Queens,Sunnyside Q,40.740176,-73.926916,42.0
141,Queens,East Elmhurst,40.764073,-73.867041,60.0
142,Queens,Maspeth,40.725427,-73.896217,85.0
143,Queens,Ridgewood,40.708323,-73.901435,88.0
144,Queens,Glendale,40.702762,-73.870742,55.0
145,Queens,Rego Park,40.728974,-73.857827,92.0
146,Queens,Woodhaven,40.689887,-73.858110,76.0
147,Queens,Ozone Park,40.680708,-73.843203,84.0
148,Queens,South Ozone Park,40.668550,-73.809865,62.0
149,Queens,College Point,40.784903,-73.843045,89.0
150,Queens,Whitestone,40.781291,-73.814202,54.0
151,Queens,Bayside,40.766041,-73.774274,123.0
152,Queens,Auburndale,40.761730,-73.791762,46.0
153,Queens,Little Neck,40.770826,-73.738898,102.0
154,Queens,Douglaston,40.766846,-73.742498,63.0
155,Queens,Glen Oaks,40.749441,-73.715481,33.0
156,Queens,Bellerose,40.728573,-73.720128,52.0
157,Queens,Kew Gardens Hills,40.722578,-73.820878,18.0
158,Queens,Fresh Meadows,40.734394,-73.782713,64.0
159,Queens,Briarwood,40.710935,-73.811748,59.0
160,Queens,Jamaica Center,40.704657,-73.796902,94.0
161,Queens,Oakland Gardens,40.745619,-73.754950,64.0
162,Queens,Queens Village,40.718893,-73.738715,46.0
163,Queens,Hollis,40.711243,-73.759250,44.0
164,Queens,South Jamaica,40.696911,-73.790426,26.0
165,Queens,St. Albans,40.694445,-73.758676,33.0
166,Queens,Rochdale,40.675211,-73.772588,13.0
167,Queens,Springfield Gardens,40.666230,-73.760421,15.0
168,Queens,Cambria Heights,40.692775,-73.735269,24.0
169,Queens,Rosedale,40.659816,-73.735261,23.0
170,Queens,Far Rockaway,40.603134,-73.754980,51.0
171,Queens,Broad Channel,40.603027,-73.820055,5.0
172,Queens,Breezy Point,40.557401,-73.925512,5.0
173,Queens,Steinway,40.775923,-73.902290,72.0
174,Queens,Beechhurst,40.792781,-73.804365,19.0
175,Queens,Bay Terrace Q,40.782843,-73.776802,37.0
176,Queens,Edgemere,40.595642,-73.776133,15.0
177,Queens,Arverne,40.589144,-73.791992,42.0
178,Queens,Rockaway Beach,40.582802,-73.822361,95.0
179,Queens,Neponsit,40.572037,-73.857547,28.0
180,Queens,Murray Hill Q,40.764126,-73.812763,47.0
181,Queens,Floral Park,40.741378,-73.708847,39.0
182,Queens,Holliswood,40.720957,-73.767142,30.0
183,Queens,Jamaica Estates,40.716805,-73.787227,32.0
184,Queens,Queensboro Hill,40.744572,-73.825809,42.0
185,Queens,Hillcrest,40.723825,-73.797603,35.0
186,Queens,Ravenswood,40.761705,-73.931575,79.0
187,Queens,Lindenwood,40.663918,-73.849638,14.0
188,Queens,Laurelton,40.667884,-73.740256,27.0
189,Queens,Lefrak City,40.736075,-73.862525,74.0
190,Queens,Belle Harbor,40.576156,-73.854018,45.0
191,Queens,Rockaway Park,40.580343,-73.841534,72.0
192,Queens,Somerville,40.597711,-73.796648,2.0
193,Queens,Brookville,40.660003,-73.751753,1.0
194,Queens,Bellaire,40.733014,-73.738892,15.0
195,Queens,North Corona,40.754071,-73.857518,70.0
196,Queens,Forest Hills Gardens,40.714611,-73.841022,70.0
197,Staten Island,St. George,40.644982,-74.079353,60.0
198,Staten Island,New Brighton,40.640615,-74.087017,24.0
199,Staten Island,Stapleton,40.626928,-74.077902,39.0
200,Staten Island,Sunnyside SI,40.615305,-74.069805,29.0
201,Staten Island,West Brighton,40.631879,-74.107182,43.0
202,Staten Island,Grymes Hill,40.624185,-74.087248,3.0
203,Staten Island,Todt Hill,40.597069,-74.111329,1.0
204,Staten Island,South Beach,40.580247,-74.079553,8.0
205,Staten Island,Port Richmond,40.633669,-74.129434,49.0
206,Staten Island,Mariner's Harbor,40.632546,-74.150085,6.0
207,Staten Island,Port Ivory,40.639683,-74.174645,1.0
208,Staten Island,Castleton Corners,40.613336,-74.119181,14.0
209,Staten Island,New Springville,40.594252,-74.164960,22.0
210,Staten Island,Travis,40.586314,-74.190737,13.0
211,Staten Island,New Dorp,40.572572,-74.116479,39.0
212,Staten Island,Oakwood,40.558462,-74.121566,5.0
213,Staten Island,Great Kills,40.549480,-74.149324,19.0
214,Staten Island,Eltingville,40.542231,-74.164331,33.0
215,Staten Island,Annadale,40.538114,-74.178549,11.0
216,Staten Island,Woodrow,40.541968,-74.205246,17.0
217,Staten Island,Tottenville,40.505334,-74.246569,7.0
218,Staten Island,Tompkinsville,40.637316,-74.080554,63.0
219,Staten Island,Silver Lake,40.619193,-74.096290,4.0
220,Staten Island,Sunnyside,40.612760,-74.097126,57.0
221,Brooklyn,Ditmas Park,40.643675,-73.961013,100.0
222,Brooklyn,Wingate,40.660947,-73.937187,72.0
223,Brooklyn,Rugby,40.655572,-73.926882,67.0
224,Staten Island,Park Hill,40.609190,-74.080157,6.0
225,Staten Island,Westerleigh,40.621090,-74.133041,40.0
226,Staten Island,Graniteville,40.620172,-74.153152,3.0
227,Staten Island,Arlington,40.635325,-74.165104,6.0
228,Staten Island,Arrochar,40.596313,-74.067124,25.0
229,Staten Island,Grasmere,40.598268,-74.076674,23.0
230,Staten Island,Old Town,40.596329,-74.087511,21.0
231,Staten Island,Dongan Hills,40.588673,-74.096399,29.0
232,Staten Island,Midland Beach,40.573527,-74.093483,11.0
233,Staten Island,Grant City,40.576216,-74.105856,42.0
234,Staten Island,New Dorp Beach,40.564255,-74.104327,11.0
235,Staten Island,Bay Terrace,40.553988,-74.139166,8.0
236,Staten Island,Huguenot,40.531912,-74.191741,10.0
237,Staten Island,Pleasant Plains,40.524699,-74.219831,15.0
238,Staten Island,Butler Manor,40.506082,-74.229504,6.0
239,Staten Island,Charleston,40.530531,-74.232158,26.0
240,Staten Island,Rossville,40.549404,-74.215729,12.0
241,Staten Island,Arden Heights,40.549286,-74.185887,6.0
242,Staten Island,Greenridge,40.555295,-74.170794,7.0
243,Staten Island,Heartland Village,40.589139,-74.159022,12.0
244,Staten Island,Chelsea SI,40.594726,-74.189560,7.0
245,Staten Island,Bloomfield,40.605779,-74.187256,4.0
246,Staten Island,Bulls Head,40.609592,-74.159409,48.0
247,Manhattan,Carnegie Hill,40.782683,-73.953256,140.0
248,Manhattan,Noho,40.723259,-73.988434,150.0
249,Manhattan,Civic Center,40.715229,-74.005415,150.0
250,Manhattan,Midtown South,40.748510,-73.988713,150.0
251,Staten Island,Richmond Town,40.569606,-74.134057,4.0
252,Staten Island,Shore Acres,40.609719,-74.066678,25.0
253,Staten Island,Clifton,40.619178,-74.072642,28.0
254,Staten Island,Concord,40.604473,-74.084024,9.0
255,Staten Island,Emerson Hill,40.606794,-74.097762,NaN
256,Staten Island,Randall Manor,40.635630,-74.098051,5.0
257,Staten Island,Howland Hook,40.638433,-74.186223,NaN
258,Staten Island,Elm Park,40.630147,-74.141817,60.0
259,Brooklyn,Remsen Village,40.652117,-73.916653,25.0
260,Brooklyn,New Lots,40.662744,-73.885118,24.0
261,Brooklyn,Paerdegat Basin,40.631318,-73.902335,6.0
262,Brooklyn,Mill Basin,40.615974,-73.915154,50.0
263,Queens,Jamaica Hills,40.711460,-73.796465,74.0
264,Queens,Utopia,40.733500,-73.796717,46.0
265,Queens,Pomonok,40.734936,-73.804861,26.0
266,Queens,Astoria Heights,40.770317,-73.894680,16.0
267,Bronx,Claremont Village,40.831428,-73.901199,38.0
268,Bronx,Concourse Village,40.824780,-73.915847,83.0
269,Bronx,Mount Eden,40.843826,-73.916556,76.0
270,Bronx,Mount Hope,40.848842,-73.908299,62.0
271,Manhattan,Sutton Place,40.760280,-73.963556,150.0
272,Queens,Hunters Point,40.743414,-73.953868,118.0
273,Manhattan,Turtle Bay,40.752042,-73.967708,150.0
274,Manhattan,Tudor City,40.746917,-73.971219,131.0
275,Manhattan,Stuyvesant Town,40.731000,-73.974052,69.0
276,Manhattan,Flatiron,40.739673,-73.990947,150.0
277,Queens,Sunnyside Gardens,40.745652,-73.918193,150.0
278,Queens,Blissville,40.737251,-73.932442,71.0
279,Brooklyn,Fulton Ferry,40.703281,-73.995508,109.0
280,Brooklyn,Vinegar Hill,40.703321,-73.981116,75.0
281,Brooklyn,Weeksville,40.675040,-73.930531,65.0
282,Brooklyn,Broadway Junction,40.677861,-73.903317,45.0
283,Brooklyn,Dumbo,40.703176,-73.988753,123.0
284,Staten Island,Manor Heights,40.601810,-74.120594,12.0
285,Staten Island,Willowbrook,40.603707,-74.132084,6.0
286,Staten Island,Sandy Ground,40.541140,-74.217766,11.0
287,Staten Island,Egbertville,40.579119,-74.127272,4.0
288,Queens,Roxbury,40.567376,-73.892138,7.0
289,Brooklyn,Homecrest,40.598525,-73.959185,87.0
290,Queens,Middle Village,40.716415,-73.881143,66.0
291,Staten Island,Prince's Bay,40.526264,-74.201526,11.0
292,Staten Island,Lighthouse Hill,40.576506,-74.137927,5.0
293,Staten Island,Richmond Valley,40.519541,-74.229571,10.0
294,Queens,Malba,40.790602,-73.826678,4.0
295,Brooklyn,Highland Park,40.681999,-73.890346,18.0
296,Brooklyn,Madison,40.609378,-73.948415,16.0
297,Bronx,Bronxdale,40.852723,-73.861726,63.0
298,Bronx,Allerton,40.865788,-73.859319,65.0
299,Bronx,Kingsbridge Heights,40.870392,-73.901523,78.0
300,Brooklyn,Erasmus,40.646926,-73.948177,71.0
301,Manhattan,Hudson Yards,40.756658,-74.000111,130.0
302,Queens,Hammels,40.587338,-73.805530,67.0
303,Queens,Bayswater,40.611322,-73.765968,2.0
304,Queens,Queensbridge,40.756091,-73.945631,67.0
305,Staten Island,Fox Hills,40.617311,-74.081740,4.0

In [124]:
nbhoods_new['Venue_density']=nbhoods_new['Number_of_venues']/908

In [125]:
nbhoods_new

,Borough,Neighborhood,Latitude,Longitude,Number_of_venues,Venue_density
0,Bronx,Wakefield,40.894705,-73.847201,11.0,0.012115
1,Bronx,Co-op City,40.874294,-73.829939,16.0,0.017621
2,Bronx,Eastchester,40.887556,-73.827806,26.0,0.028634
3,Bronx,Fieldston,40.895437,-73.905643,13.0,0.014317
4,Bronx,Riverdale,40.890834,-73.912585,39.0,0.042952
5,Bronx,Kingsbridge,40.881687,-73.902818,119.0,0.131057
6,Manhattan,Marble Hill,40.876551,-73.910660,71.0,0.078194
7,Bronx,Woodlawn,40.898273,-73.867315,48.0,0.052863
8,Bronx,Norwood,40.877224,-73.879391,78.0,0.085903
9,Bronx,Williamsbridge,40.881039,-73.857446,38.0,0.041850
10,Bronx,Baychester,40.866858,-73.835798,28.0,0.030837
11,Bronx,Pelham Parkway,40.857413,-73.854756,37.0,0.040749
12,Bronx,City Island,40.847247,-73.786488,46.0,0.050661
13,Bronx,Bedford Park,40.870185,-73.885512,86.0,0.094714
14,Bronx,University Heights,40.855727,-73.910416,71.0,0.078194
15,Bronx,Morris Heights,40.847898,-73.919672,56.0,0.061674
16,Bronx,Fordham,40.860997,-73.896427,136.0,0.149780
17,Bronx,East Tremont,40.842696,-73.887356,35.0,0.038546
18,Bronx,West Farms,40.839475,-73.877745,40.0,0.044053
19,Bronx,High Bridge,40.836623,-73.926102,74.0,0.081498
20,Bronx,Melrose,40.819754,-73.909422,75.0,0.082599
21,Bronx,Mott Haven,40.806239,-73.916100,58.0,0.063877
22,Bronx,Port Morris,40.801664,-73.913221,16.0,0.017621
23,Bronx,Longwood,40.815099,-73.895788,54.0,0.059471
24,Bronx,Hunts Point,40.809730,-73.883315,13.0,0.014317
25,Bronx,Morrisania,40.823592,-73.901506,70.0,0.077093
26,Bronx,Soundview,40.821012,-73.865746,17.0,0.018722
27,Bronx,Clason Point,40.806551,-73.854144,11.0,0.012115
28,Bronx,Throgs Neck,40.815109,-73.816350,11.0,0.012115
29,Bronx,Country Club,40.844246,-73.824099,15.0,0.016520
30,Bronx,Parkchester,40.837938,-73.856003,83.0,0.091410
31,Bronx,Westchester Square,40.840619,-73.842194,85.0,0.093612
32,Bronx,Van Nest,40.843608,-73.866299,60.0,0.066079
33,Bronx,Morris Park,40.847549,-73.850402,74.0,0.081498
34,Bronx,Belmont,40.857277,-73.888452,149.0,0.164097
35,Bronx,Spuyten Duyvil,40.881395,-73.917190,25.0,0.027533
36,Bronx,North Riverdale,40.908543,-73.904531,27.0,0.029736
37,Bronx,Pelham Bay,40.850641,-73.832074,54.0,0.059471
38,Bronx,Schuylerville,40.826580,-73.826203,37.0,0.040749
39,Bronx,Edgewater Park,40.821986,-73.813885,20.0,0.022026
40,Bronx,Castle Hill,40.819014,-73.848027,7.0,0.007709
41,Bronx,Olinville,40.871371,-73.863324,51.0,0.056167
42,Bronx,Pelham Gardens,40.862966,-73.841612,18.0,0.019824
43,Bronx,Concourse,40.834284,-73.915589,76.0,0.083700
44,Bronx,Unionport,40.829774,-73.850535,71.0,0.078194
45,Bronx,Edenwald,40.884561,-73.848083,4.0,0.004405
46,Brooklyn,Bay Ridge,40.625801,-74.030621,127.0,0.139868
47,Brooklyn,Bensonhurst,40.611009,-73.995180,82.0,0.090308
48,Brooklyn,Sunset Park,40.645103,-74.010316,88.0,0.096916
49,Brooklyn,Greenpoint,40.730201,-73.954241,150.0,0.165198
50,Brooklyn,Gravesend,40.595260,-73.973471,53.0,0.058370
51,Brooklyn,Brighton Beach,40.576825,-73.965094,83.0,0.091410
52,Brooklyn,Sheepshead Bay,40.586890,-73.943186,76.0,0.083700
53,Brooklyn,Manhattan Terrace,40.614433,-73.957438,74.0,0.081498
54,Brooklyn,Flatbush,40.636326,-73.958401,71.0,0.078194
55,Brooklyn,Crown Heights,40.670829,-73.943291,68.0,0.074890
56,Brooklyn,East Flatbush,40.641718,-73.936103,19.0,0.020925
57,Brooklyn,Kensington,40.642382,-73.980421,86.0,0.094714
58,Brooklyn,Windsor Terrace,40.656946,-73.980073,77.0,0.084802
59,Brooklyn,Prospect Heights,40.676822,-73.964859,132.0,0.145374
60,Brooklyn,Brownsville,40.663950,-73.910235,56.0,0.061674
61,Brooklyn,Williamsburg,40.707144,-73.958115,81.0,0.089207
62,Brooklyn,Bushwick,40.698116,-73.925258,115.0,0.126652
63,Brooklyn,Bedford Stuyvesant,40.687232,-73.941785,82.0,0.090308
64,Brooklyn,Brooklyn Heights,40.695864,-73.993782,149.0,0.164097
65,Brooklyn,Cobble Hill,40.687920,-73.998561,150.0,0.165198
66,Brooklyn,Carroll Gardens,40.680540,-73.994654,150.0,0.165198
67,Brooklyn,Red Hook,40.676253,-74.012759,61.0,0.067181
68,Brooklyn,Gowanus,40.673931,-73.994441,116.0,0.127753
69,Brooklyn,Fort Greene,40.688527,-73.972906,118.0,0.129956
70,Brooklyn,Park Slope,40.672321,-73.977050,115.0,0.126652
71,Brooklyn,Cypress Hills,40.682391,-73.876616,68.0,0.074890
72,Brooklyn,East New York,40.669926,-73.880699,20.0,0.022026
73,Brooklyn,Starrett City,40.647589,-73.879370,11.0,0.012115
74,Brooklyn,Canarsie,40.635564,-73.902093,6.0,0.006608
75,Brooklyn,Flatlands,40.630446,-73.929113,18.0,0.019824
76,Brooklyn,Mill Island,40.606336,-73.908186,2.0,0.002203
77,Brooklyn,Manhattan Beach,40.577914,-73.943537,19.0,0.020925
78,Brooklyn,Coney Island,40.574293,-73.988683,53.0,0.058370
79,Brooklyn,Bath Beach,40.599519,-73.998752,98.0,0.107930
80,Brooklyn,Borough Park,40.633131,-73.990498,69.0,0.075991
81,Brooklyn,Dyker Heights,40.619219,-74.019314,58.0,0.063877
82,Brooklyn,Gerritsen Beach,40.590848,-73.930102,21.0,0.023128
83,Brooklyn,Marine Park,40.609748,-73.931344,8.0,0.008811
84,Brooklyn,Clinton Hill,40.693229,-73.967843,149.0,0.164097
85,Brooklyn,Sea Gate,40.576375,-74.007873,6.0,0.006608
86,Brooklyn,Downtown,40.690844,-73.983463,149.0,0.164097
87,Brooklyn,Boerum Hill,40.685683,-73.983748,144.0,0.158590
88,Brooklyn,Prospect Lefferts Gardens,40.658420,-73.954899,99.0,0.109031
89,Brooklyn,Ocean Hill,40.678403,-73.913068,73.0,0.080396
90,Brooklyn,City Line,40.678570,-73.867976,87.0,0.095815
91,Brooklyn,Bergen Beach,40.615150,-73.898556,6.0,0.006608
92,Brooklyn,Midwood,40.625596,-73.957595,61.0,0.067181
93,Brooklyn,Prospect Park South,40.647009,-73.962613,103.0,0.113436
94,Brooklyn,Georgetown,40.623845,-73.916075,27.0,0.029736
95,Brooklyn,East Williamsburg,40.708492,-73.938858,116.0,0.127753
96,Brooklyn,North Side,40.714823,-73.958809,149.0,0.164097
97,Brooklyn,South Side,40.710861,-73.958001,149.0,0.164097
98,Brooklyn,Ocean Parkway,40.613060,-73.968367,68.0,0.074890
99,Brooklyn,Fort Hamilton,40.614768,-74.031979,107.0,0.117841
100,Manhattan,Chinatown,40.715618,-73.994279,150.0,0.165198
101,Manhattan,Washington Heights,40.851903,-73.936900,135.0,0.148678
102,Manhattan,Inwood,40.867684,-73.921210,103.0,0.113436
103,Manhattan,Hamilton Heights,40.823604,-73.949688,109.0,0.120044
104,Manhattan,Manhattanville,40.816934,-73.957385,98.0,0.107930
105,Manhattan,Central Harlem,40.815976,-73.943211,95.0,0.104626
106,Manhattan,East Harlem,40.792249,-73.944182,93.0,0.102423
107,Manhattan,Upper East Side,40.775639,-73.960508,147.0,0.161894
108,Manhattan,Yorkville,40.775930,-73.947118,150.0,0.165198
109,Manhattan,Lenox Hill,40.768113,-73.958860,149.0,0.164097
110,Manhattan,Roosevelt Island,40.762160,-73.949168,79.0,0.087004
111,Manhattan,Upper West Side,40.787658,-73.977059,150.0,0.165198
112,Manhattan,Lincoln Square,40.773529,-73.985338,146.0,0.160793
113,Manhattan,Clinton,40.759101,-73.996119,150.0,0.165198
114,Manhattan,Midtown,40.754691,-73.981669,149.0,0.164097
115,Manhattan,Murray Hill M,40.748303,-73.978332,100.0,0.110132
116,Manhattan,Chelsea M,40.744035,-74.003116,150.0,0.165198
117,Manhattan,Greenwich Village,40.726933,-73.999914,150.0,0.165198
118,Manhattan,East Village,40.727847,-73.982226,150.0,0.165198
119,Manhattan,Lower East Side,40.717807,-73.980890,97.0,0.106828
120,Manhattan,Tribeca,40.721522,-74.010683,141.0,0.155286
121,Manhattan,Little Italy,40.719324,-73.997305,150.0,0.165198
122,Manhattan,Soho,40.722184,-74.000657,150.0,0.165198
123,Manhattan,West Village,40.734434,-74.006180,150.0,0.165198
124,Manhattan,Manhattan Valley,40.797307,-73.964286,99.0,0.109031
125,Manhattan,Morningside Heights,40.808000,-73.963896,93.0,0.102423
126,Manhattan,Gramercy,40.737210,-73.981376,148.0,0.162996
127,Manhattan,Battery Park City,40.711932,-74.016869,141.0,0.155286
128,Manhattan,Financial District,40.707107,-74.010665,148.0,0.162996
129,Queens,Astoria,40.768509,-73.915654,150.0,0.165198
130,Queens,Woodside,40.746349,-73.901842,132.0,0.145374
131,Queens,Jackson Heights,40.751981,-73.882821,128.0,0.140969
132,Queens,Elmhurst,40.744049,-73.881656,84.0,0.092511
133,Queens,Howard Beach,40.654225,-73.838138,87.0,0.095815
134,Queens,Corona,40.742382,-73.856825,70.0,0.077093
135,Queens,Bay Terrace SI,40.725264,-73.844475,41.0,0.045154
136,Queens,Kew Gardens,40.705179,-73.829819,103.0,0.113436
137,Queens,Richmond Hill,40.697947,-73.831833,77.0,0.084802
138,Queens,Flushing,40.764454,-73.831773,107.0,0.117841
139,Queens,Long Island City,40.750217,-73.939202,123.0,0.135463
140,Queens,Sunnyside Q,40.740176,-73.926916,42.0,0.046256
141,Queens,East Elmhurst,40.764073,-73.867041,60.0,0.066079
142,Queens,Maspeth,40.725427,-73.896217,85.0,0.093612
143,Queens,Ridgewood,40.708323,-73.901435,88.0,0.096916
144,Queens,Glendale,40.702762,-73.870742,55.0,0.060573
145,Queens,Rego Park,40.728974,-73.857827,92.0,0.101322
146,Queens,Woodhaven,40.689887,-73.858110,76.0,0.083700
147,Queens,Ozone Park,40.680708,-73.843203,84.0,0.092511
148,Queens,South Ozone Park,40.668550,-73.809865,62.0,0.068282
149,Queens,College Point,40.784903,-73.843045,89.0,0.098018
150,Queens,Whitestone,40.781291,-73.814202,54.0,0.059471
151,Queens,Bayside,40.766041,-73.774274,123.0,0.135463
152,Queens,Auburndale,40.761730,-73.791762,46.0,0.050661
153,Queens,Little Neck,40.770826,-73.738898,102.0,0.112335
154,Queens,Douglaston,40.766846,-73.742498,63.0,0.069383
155,Queens,Glen Oaks,40.749441,-73.715481,33.0,0.036344
156,Queens,Bellerose,40.728573,-73.720128,52.0,0.057269
157,Queens,Kew Gardens Hills,40.722578,-73.820878,18.0,0.019824
158,Queens,Fresh Meadows,40.734394,-73.782713,64.0,0.070485
159,Queens,Briarwood,40.710935,-73.811748,59.0,0.064978
160,Queens,Jamaica Center,40.704657,-73.796902,94.0,0.103524
161,Queens,Oakland Gardens,40.745619,-73.754950,64.0,0.070485
162,Queens,Queens Village,40.718893,-73.738715,46.0,0.050661
163,Queens,Hollis,40.711243,-73.759250,44.0,0.048458
164,Queens,South Jamaica,40.696911,-73.790426,26.0,0.028634
165,Queens,St. Albans,40.694445,-73.758676,33.0,0.036344
166,Queens,Rochdale,40.675211,-73.772588,13.0,0.014317
167,Queens,Springfield Gardens,40.666230,-73.760421,15.0,0.016520
168,Queens,Cambria Heights,40.692775,-73.735269,24.0,0.026432
169,Queens,Rosedale,40.659816,-73.735261,23.0,0.025330
170,Queens,Far Rockaway,40.603134,-73.754980,51.0,0.056167
171,Queens,Broad Channel,40.603027,-73.820055,5.0,0.005507
172,Queens,Breezy Point,40.557401,-73.925512,5.0,0.005507
173,Queens,Steinway,40.775923,-73.902290,72.0,0.079295
174,Queens,Beechhurst,40.792781,-73.804365,19.0,0.020925
175,Queens,Bay Terrace Q,40.782843,-73.776802,37.0,0.040749
176,Queens,Edgemere,40.595642,-73.776133,15.0,0.016520
177,Queens,Arverne,40.589144,-73.791992,42.0,0.046256
178,Queens,Rockaway Beach,40.582802,-73.822361,95.0,0.104626
179,Queens,Neponsit,40.572037,-73.857547,28.0,0.030837
180,Queens,Murray Hill Q,40.764126,-73.812763,47.0,0.051762
181,Queens,Floral Park,40.741378,-73.708847,39.0,0.042952
182,Queens,Holliswood,40.720957,-73.767142,30.0,0.033040
183,Queens,Jamaica Estates,40.716805,-73.787227,32.0,0.035242
184,Queens,Queensboro Hill,40.744572,-73.825809,42.0,0.046256
185,Queens,Hillcrest,40.723825,-73.797603,35.0,0.038546
186,Queens,Ravenswood,40.761705,-73.931575,79.0,0.087004
187,Queens,Lindenwood,40.663918,-73.849638,14.0,0.015419
188,Queens,Laurelton,40.667884,-73.740256,27.0,0.029736
189,Queens,Lefrak City,40.736075,-73.862525,74.0,0.081498
190,Queens,Belle Harbor,40.576156,-73.854018,45.0,0.049559
191,Queens,Rockaway Park,40.580343,-73.841534,72.0,0.079295
192,Queens,Somerville,40.597711,-73.796648,2.0,0.002203
193,Queens,Brookville,40.660003,-73.751753,1.0,0.001101
194,Queens,Bellaire,40.733014,-73.738892,15.0,0.016520
195,Queens,North Corona,40.754071,-73.857518,70.0,0.077093
196,Queens,Forest Hills Gardens,40.714611,-73.841022,70.0,0.077093
197,Staten Island,St. George,40.644982,-74.079353,60.0,0.066079
198,Staten Island,New Brighton,40.640615,-74.087017,24.0,0.026432
199,Staten Island,Stapleton,40.626928,-74.077902,39.0,0.042952
200,Staten Island,Sunnyside SI,40.615305,-74.069805,29.0,0.031938
201,Staten Island,West Brighton,40.631879,-74.107182,43.0,0.047357
202,Staten Island,Grymes Hill,40.624185,-74.087248,3.0,0.003304
203,Staten Island,Todt Hill,40.597069,-74.111329,1.0,0.001101
204,Staten Island,South Beach,40.580247,-74.079553,8.0,0.008811
205,Staten Island,Port Richmond,40.633669,-74.129434,49.0,0.053965
206,Staten Island,Mariner's Harbor,40.632546,-74.150085,6.0,0.006608
207,Staten Island,Port Ivory,40.639683,-74.174645,1.0,0.001101
208,Staten Island,Castleton Corners,40.613336,-74.119181,14.0,0.015419
209,Staten Island,New Springville,40.594252,-74.164960,22.0,0.024229
210,Staten Island,Travis,40.586314,-74.190737,13.0,0.014317
211,Staten Island,New Dorp,40.572572,-74.116479,39.0,0.042952
212,Staten Island,Oakwood,40.558462,-74.121566,5.0,0.005507
213,Staten Island,Great Kills,40.549480,-74.149324,19.0,0.020925
214,Staten Island,Eltingville,40.542231,-74.164331,33.0,0.036344
215,Staten Island,Annadale,40.538114,-74.178549,11.0,0.012115
216,Staten Island,Woodrow,40.541968,-74.205246,17.0,0.018722
217,Staten Island,Tottenville,40.505334,-74.246569,7.0,0.007709
218,Staten Island,Tompkinsville,40.637316,-74.080554,63.0,0.069383
219,Staten Island,Silver Lake,40.619193,-74.096290,4.0,0.004405
220,Staten Island,Sunnyside,40.612760,-74.097126,57.0,0.062775
221,Brooklyn,Ditmas Park,40.643675,-73.961013,100.0,0.110132
222,Brooklyn,Wingate,40.660947,-73.937187,72.0,0.079295
223,Brooklyn,Rugby,40.655572,-73.926882,67.0,0.073789
224,Staten Island,Park Hill,40.609190,-74.080157,6.0,0.006608
225,Staten Island,Westerleigh,40.621090,-74.133041,40.0,0.044053
226,Staten Island,Graniteville,40.620172,-74.153152,3.0,0.003304
227,Staten Island,Arlington,40.635325,-74.165104,6.0,0.006608
228,Staten Island,Arrochar,40.596313,-74.067124,25.0,0.027533
229,Staten Island,Grasmere,40.598268,-74.076674,23.0,0.025330
230,Staten Island,Old Town,40.596329,-74.087511,21.0,0.023128
231,Staten Island,Dongan Hills,40.588673,-74.096399,29.0,0.031938
232,Staten Island,Midland Beach,40.573527,-74.093483,11.0,0.012115
233,Staten Island,Grant City,40.576216,-74.105856,42.0,0.046256
234,Staten Island,New Dorp Beach,40.564255,-74.104327,11.0,0.012115
235,Staten Island,Bay Terrace,40.553988,-74.139166,8.0,0.008811
236,Staten Island,Huguenot,40.531912,-74.191741,10.0,0.011013
237,Staten Island,Pleasant Plains,40.524699,-74.219831,15.0,0.016520
238,Staten Island,Butler Manor,40.506082,-74.229504,6.0,0.006608
239,Staten Island,Charleston,40.530531,-74.232158,26.0,0.028634
240,Staten Island,Rossville,40.549404,-74.215729,12.0,0.013216
241,Staten Island,Arden Heights,40.549286,-74.185887,6.0,0.006608
242,Staten Island,Greenridge,40.555295,-74.170794,7.0,0.007709
243,Staten Island,Heartland Village,40.589139,-74.159022,12.0,0.013216
244,Staten Island,Chelsea SI,40.594726,-74.189560,7.0,0.007709
245,Staten Island,Bloomfield,40.605779,-74.187256,4.0,0.004405
246,Staten Island,Bulls Head,40.609592,-74.159409,48.0,0.052863
247,Manhattan,Carnegie Hill,40.782683,-73.953256,140.0,0.154185
248,Manhattan,Noho,40.723259,-73.988434,150.0,0.165198
249,Manhattan,Civic Center,40.715229,-74.005415,150.0,0.165198
250,Manhattan,Midtown South,40.748510,-73.988713,150.0,0.165198
251,Staten Island,Richmond Town,40.569606,-74.134057,4.0,0.004405
252,Staten Island,Shore Acres,40.609719,-74.066678,25.0,0.027533
253,Staten Island,Clifton,40.619178,-74.072642,28.0,0.030837
254,Staten Island,Concord,40.604473,-74.084024,9.0,0.009912
255,Staten Island,Emerson Hill,40.606794,-74.097762,NaN,NaN
256,Staten Island,Randall Manor,40.635630,-74.098051,5.0,0.005507
257,Staten Island,Howland Hook,40.638433,-74.186223,NaN,NaN
258,Staten Island,Elm Park,40.630147,-74.141817,60.0,0.066079
259,Brooklyn,Remsen Village,40.652117,-73.916653,25.0,0.027533
260,Brooklyn,New Lots,40.662744,-73.885118,24.0,0.026432
261,Brooklyn,Paerdegat Basin,40.631318,-73.902335,6.0,0.006608
262,Brooklyn,Mill Basin,40.615974,-73.915154,50.0,0.055066
263,Queens,Jamaica Hills,40.711460,-73.796465,74.0,0.081498
264,Queens,Utopia,40.733500,-73.796717,46.0,0.050661
265,Queens,Pomonok,40.734936,-73.804861,26.0,0.028634
266,Queens,Astoria Heights,40.770317,-73.894680,16.0,0.017621
267,Bronx,Claremont Village,40.831428,-73.901199,38.0,0.041850
268,Bronx,Concourse Village,40.824780,-73.915847,83.0,0.091410
269,Bronx,Mount Eden,40.843826,-73.916556,76.0,0.083700
270,Bronx,Mount Hope,40.848842,-73.908299,62.0,0.068282
271,Manhattan,Sutton Place,40.760280,-73.963556,150.0,0.165198
272,Queens,Hunters Point,40.743414,-73.953868,118.0,0.129956
273,Manhattan,Turtle Bay,40.752042,-73.967708,150.0,0.165198
274,Manhattan,Tudor City,40.746917,-73.971219,131.0,0.144273
275,Manhattan,Stuyvesant Town,40.731000,-73.974052,69.0,0.075991
276,Manhattan,Flatiron,40.739673,-73.990947,150.0,0.165198
277,Queens,Sunnyside Gardens,40.745652,-73.918193,150.0,0.165198
278,Queens,Blissville,40.737251,-73.932442,71.0,0.078194
279,Brooklyn,Fulton Ferry,40.703281,-73.995508,109.0,0.120044
280,Brooklyn,Vinegar Hill,40.703321,-73.981116,75.0,0.082599
281,Brooklyn,Weeksville,40.675040,-73.930531,65.0,0.071586
282,Brooklyn,Broadway Junction,40.677861,-73.903317,45.0,0.049559
283,Brooklyn,Dumbo,40.703176,-73.988753,123.0,0.135463
284,Staten Island,Manor Heights,40.601810,-74.120594,12.0,0.013216
285,Staten Island,Willowbrook,40.603707,-74.132084,6.0,0.006608
286,Staten Island,Sandy Ground,40.541140,-74.217766,11.0,0.012115
287,Staten Island,Egbertville,40.579119,-74.127272,4.0,0.004405
288,Queens,Roxbury,40.567376,-73.892138,7.0,0.007709
289,Brooklyn,Homecrest,40.598525,-73.959185,87.0,0.095815
290,Queens,Middle Village,40.716415,-73.881143,66.0,0.072687
291,Staten Island,Prince's Bay,40.526264,-74.201526,11.0,0.012115
292,Staten Island,Lighthouse Hill,40.576506,-74.137927,5.0,0.005507
293,Staten Island,Richmond Valley,40.519541,-74.229571,10.0,0.011013
294,Queens,Malba,40.790602,-73.826678,4.0,0.004405
295,Brooklyn,Highland Park,40.681999,-73.890346,18.0,0.019824
296,Brooklyn,Madison,40.609378,-73.948415,16.0,0.017621
297,Bronx,Bronxdale,40.852723,-73.861726,63.0,0.069383
298,Bronx,Allerton,40.865788,-73.859319,65.0,0.071586
299,Bronx,Kingsbridge Heights,40.870392,-73.901523,78.0,0.085903
300,Brooklyn,Erasmus,40.646926,-73.948177,71.0,0.078194
301,Manhattan,Hudson Yards,40.756658,-74.000111,130.0,0.143172
302,Queens,Hammels,40.587338,-73.805530,67.0,0.073789
303,Queens,Bayswater,40.611322,-73.765968,2.0,0.002203
304,Queens,Queensbridge,40.756091,-73.945631,67.0,0.073789
305,Staten Island,Fox Hills,40.617311,-74.081740,4.0,0.004405

In [126]:
nbhoods_new[nbhoods_new['Neighborhood'].isin(nbhoods_with_restaurants)==False]

,Borough,Neighborhood,Latitude,Longitude,Number_of_venues,Venue_density
76,Brooklyn,Mill Island,40.606336,-73.908186,2.0,0.002203
91,Brooklyn,Bergen Beach,40.615150,-73.898556,6.0,0.006608
172,Queens,Breezy Point,40.557401,-73.925512,5.0,0.005507
192,Queens,Somerville,40.597711,-73.796648,2.0,0.002203
193,Queens,Brookville,40.660003,-73.751753,1.0,0.001101
202,Staten Island,Grymes Hill,40.624185,-74.087248,3.0,0.003304
203,Staten Island,Todt Hill,40.597069,-74.111329,1.0,0.001101
204,Staten Island,South Beach,40.580247,-74.079553,8.0,0.008811
207,Staten Island,Port Ivory,40.639683,-74.174645,1.0,0.001101
210,Staten Island,Travis,40.586314,-74.190737,13.0,0.014317
212,Staten Island,Oakwood,40.558462,-74.121566,5.0,0.005507
226,Staten Island,Graniteville,40.620172,-74.153152,3.0,0.003304
238,Staten Island,Butler Manor,40.506082,-74.229504,6.0,0.006608
255,Staten Island,Emerson Hill,40.606794,-74.097762,NaN,NaN
257,Staten Island,Howland Hook,40.638433,-74.186223,NaN,NaN
285,Staten Island,Willowbrook,40.603707,-74.132084,6.0,0.006608
303,Queens,Bayswater,40.611322,-73.765968,2.0,0.002203

In [127]:
#So we have 17 nbhoods without restaurants, two of them do not have any venues at all.

In [128]:
#Add number of restaurants to the dataframe
nbhoods_new=nbhoods_new.merge(number_of_restaurants, on='Neighborhood', how='left')

In [129]:
#Find missing values and treat them with mean number of restaurants
nbhoods_new.loc[nbhoods_new['Number_of_Restaurants'].isna()]

,Borough,Neighborhood,Latitude,Longitude,Number_of_venues,Venue_density,Number_of_Restaurants
76,Brooklyn,Mill Island,40.606336,-73.908186,2.0,0.002203,NaN
91,Brooklyn,Bergen Beach,40.615150,-73.898556,6.0,0.006608,NaN
172,Queens,Breezy Point,40.557401,-73.925512,5.0,0.005507,NaN
192,Queens,Somerville,40.597711,-73.796648,2.0,0.002203,NaN
193,Queens,Brookville,40.660003,-73.751753,1.0,0.001101,NaN
202,Staten Island,Grymes Hill,40.624185,-74.087248,3.0,0.003304,NaN
203,Staten Island,Todt Hill,40.597069,-74.111329,1.0,0.001101,NaN
204,Staten Island,South Beach,40.580247,-74.079553,8.0,0.008811,NaN
207,Staten Island,Port Ivory,40.639683,-74.174645,1.0,0.001101,NaN
210,Staten Island,Travis,40.586314,-74.190737,13.0,0.014317,NaN
212,Staten Island,Oakwood,40.558462,-74.121566,5.0,0.005507,NaN
226,Staten Island,Graniteville,40.620172,-74.153152,3.0,0.003304,NaN
238,Staten Island,Butler Manor,40.506082,-74.229504,6.0,0.006608,NaN
255,Staten Island,Emerson Hill,40.606794,-74.097762,NaN,NaN,NaN
257,Staten Island,Howland Hook,40.638433,-74.186223,NaN,NaN,NaN
285,Staten Island,Willowbrook,40.603707,-74.132084,6.0,0.006608,NaN
303,Queens,Bayswater,40.611322,-73.765968,2.0,0.002203,NaN

In [130]:
nbhoods_new['Number_of_Restaurants'] = nbhoods_new['Number_of_Restaurants'].replace(np.nan, 0)

In [131]:
nbhoods_new['Number_of_venues']=nbhoods_new['Number_of_venues'].replace(np.nan, 0)

In [132]:
#Find top restaurant category for each nbhood

In [133]:
nbhoods_new=nbhoods_new.merge(grouped_cat, on='Neighborhood', how='left')

In [134]:
nbhoods_new.loc[nbhoods_new['Top Restaurant Category'].isna()]

,Borough,Neighborhood,Latitude,Longitude,Number_of_venues,Venue_density,Number_of_Restaurants,Top Restaurant Category
76,Brooklyn,Mill Island,40.606336,-73.908186,2.0,0.002203,0.0,NaN
91,Brooklyn,Bergen Beach,40.615150,-73.898556,6.0,0.006608,0.0,NaN
172,Queens,Breezy Point,40.557401,-73.925512,5.0,0.005507,0.0,NaN
192,Queens,Somerville,40.597711,-73.796648,2.0,0.002203,0.0,NaN
193,Queens,Brookville,40.660003,-73.751753,1.0,0.001101,0.0,NaN
202,Staten Island,Grymes Hill,40.624185,-74.087248,3.0,0.003304,0.0,NaN
203,Staten Island,Todt Hill,40.597069,-74.111329,1.0,0.001101,0.0,NaN
204,Staten Island,South Beach,40.580247,-74.079553,8.0,0.008811,0.0,NaN
207,Staten Island,Port Ivory,40.639683,-74.174645,1.0,0.001101,0.0,NaN
210,Staten Island,Travis,40.586314,-74.190737,13.0,0.014317,0.0,NaN
212,Staten Island,Oakwood,40.558462,-74.121566,5.0,0.005507,0.0,NaN
226,Staten Island,Graniteville,40.620172,-74.153152,3.0,0.003304,0.0,NaN
238,Staten Island,Butler Manor,40.506082,-74.229504,6.0,0.006608,0.0,NaN
255,Staten Island,Emerson Hill,40.606794,-74.097762,0.0,NaN,0.0,NaN
257,Staten Island,Howland Hook,40.638433,-74.186223,0.0,NaN,0.0,NaN
285,Staten Island,Willowbrook,40.603707,-74.132084,6.0,0.006608,0.0,NaN
303,Queens,Bayswater,40.611322,-73.765968,2.0,0.002203,0.0,NaN

In [135]:
nbhoods_new['Top Restaurant Category'] = nbhoods_new['Top Restaurant Category'].replace(np.nan, 0)

In [136]:
nbhoods_new.to_csv('working_df', index=False)

In [137]:
nbhoods_new['Top Restaurant Category'].unique() #There are 30 unique categories that represent top restaurants for each nbhood

array(['Sandwich Restaurant', 'Restaurant', 'Seafood Restaurant',
       'Mexican Restaurant', 'Vegetarian / Vegan Restaurant',
       'Steakhouse Restaurant', 'Pizza Restaurant', 'Spanish Restaurant',
       'Latin American Restaurant', 'Thai Restaurant',
       'Vietnamese Restaurant', 'Shabu-Shabu Restaurant',
       'Russian Restaurant', 'Turkish Restaurant',
       'Food Truck Restaurant', 'Yemeni Restaurant',
       'Fast Food Restaurant', 0, 'American Restaurant',
       'Southern / Soul Food Restaurant', 'Tibetan Restaurant',
       'Tapas Restaurant', 'Szechuan Restaurant', 'Taiwanese Restaurant',
       'Italian Restaurant', 'Sri Lankan Restaurant', 'Burger Restaurant',
       'Coffee Restaurant', 'Japanese Restaurant', 'Peruvian Restaurant',
       'Asian Restaurant'], dtype=object)

In [138]:
nbhoods_new

,Borough,Neighborhood,Latitude,Longitude,Number_of_venues,Venue_density,Number_of_Restaurants,Top Restaurant Category
0,Bronx,Wakefield,40.894705,-73.847201,11.0,0.012115,5.0,Sandwich Restaurant
1,Bronx,Co-op City,40.874294,-73.829939,16.0,0.017621,4.0,Restaurant
2,Bronx,Eastchester,40.887556,-73.827806,26.0,0.028634,10.0,Seafood Restaurant
3,Bronx,Fieldston,40.895437,-73.905643,13.0,0.014317,3.0,Mexican Restaurant
4,Bronx,Riverdale,40.890834,-73.912585,39.0,0.042952,10.0,Seafood Restaurant
5,Bronx,Kingsbridge,40.881687,-73.902818,119.0,0.131057,65.0,Vegetarian / Vegan Restaurant
6,Manhattan,Marble Hill,40.876551,-73.910660,71.0,0.078194,42.0,Steakhouse Restaurant
7,Bronx,Woodlawn,40.898273,-73.867315,48.0,0.052863,14.0,Pizza Restaurant
8,Bronx,Norwood,40.877224,-73.879391,78.0,0.085903,46.0,Spanish Restaurant
9,Bronx,Williamsbridge,40.881039,-73.857446,38.0,0.041850,22.0,Seafood Restaurant
10,Bronx,Baychester,40.866858,-73.835798,28.0,0.030837,13.0,Spanish Restaurant
11,Bronx,Pelham Parkway,40.857413,-73.854756,37.0,0.040749,21.0,Sandwich Restaurant
12,Bronx,City Island,40.847247,-73.786488,46.0,0.050661,19.0,Spanish Restaurant
13,Bronx,Bedford Park,40.870185,-73.885512,86.0,0.094714,56.0,Spanish Restaurant
14,Bronx,University Heights,40.855727,-73.910416,71.0,0.078194,34.0,Sandwich Restaurant
15,Bronx,Morris Heights,40.847898,-73.919672,56.0,0.061674,29.0,Spanish Restaurant
16,Bronx,Fordham,40.860997,-73.896427,136.0,0.149780,65.0,Spanish Restaurant
17,Bronx,East Tremont,40.842696,-73.887356,35.0,0.038546,24.0,Sandwich Restaurant
18,Bronx,West Farms,40.839475,-73.877745,40.0,0.044053,18.0,Sandwich Restaurant
19,Bronx,High Bridge,40.836623,-73.926102,74.0,0.081498,47.0,Seafood Restaurant
20,Bronx,Melrose,40.819754,-73.909422,75.0,0.082599,41.0,Seafood Restaurant
21,Bronx,Mott Haven,40.806239,-73.916100,58.0,0.063877,35.0,Spanish Restaurant
22,Bronx,Port Morris,40.801664,-73.913221,16.0,0.017621,6.0,Restaurant
23,Bronx,Longwood,40.815099,-73.895788,54.0,0.059471,37.0,Sandwich Restaurant
24,Bronx,Hunts Point,40.809730,-73.883315,13.0,0.014317,5.0,Spanish Restaurant
25,Bronx,Morrisania,40.823592,-73.901506,70.0,0.077093,37.0,Steakhouse Restaurant
26,Bronx,Soundview,40.821012,-73.865746,17.0,0.018722,7.0,Latin American Restaurant
27,Bronx,Clason Point,40.806551,-73.854144,11.0,0.012115,1.0,Latin American Restaurant
28,Bronx,Throgs Neck,40.815109,-73.816350,11.0,0.012115,6.0,Pizza Restaurant
29,Bronx,Country Club,40.844246,-73.824099,15.0,0.016520,7.0,Sandwich Restaurant
30,Bronx,Parkchester,40.837938,-73.856003,83.0,0.091410,45.0,Steakhouse Restaurant
31,Bronx,Westchester Square,40.840619,-73.842194,85.0,0.093612,49.0,Spanish Restaurant
32,Bronx,Van Nest,40.843608,-73.866299,60.0,0.066079,30.0,Seafood Restaurant
33,Bronx,Morris Park,40.847549,-73.850402,74.0,0.081498,47.0,Seafood Restaurant
34,Bronx,Belmont,40.857277,-73.888452,149.0,0.164097,83.0,Spanish Restaurant
35,Bronx,Spuyten Duyvil,40.881395,-73.917190,25.0,0.027533,11.0,Thai Restaurant
36,Bronx,North Riverdale,40.908543,-73.904531,27.0,0.029736,14.0,Sandwich Restaurant
37,Bronx,Pelham Bay,40.850641,-73.832074,54.0,0.059471,23.0,Thai Restaurant
38,Bronx,Schuylerville,40.826580,-73.826203,37.0,0.040749,23.0,Sandwich Restaurant
39,Bronx,Edgewater Park,40.821986,-73.813885,20.0,0.022026,11.0,Pizza Restaurant
40,Bronx,Castle Hill,40.819014,-73.848027,7.0,0.007709,2.0,Pizza Restaurant
41,Bronx,Olinville,40.871371,-73.863324,51.0,0.056167,31.0,Sandwich Restaurant
42,Bronx,Pelham Gardens,40.862966,-73.841612,18.0,0.019824,6.0,Spanish Restaurant
43,Bronx,Concourse,40.834284,-73.915589,76.0,0.083700,44.0,Spanish Restaurant
44,Bronx,Unionport,40.829774,-73.850535,71.0,0.078194,46.0,Seafood Restaurant
45,Bronx,Edenwald,40.884561,-73.848083,4.0,0.004405,1.0,Sandwich Restaurant
46,Brooklyn,Bay Ridge,40.625801,-74.030621,127.0,0.139868,63.0,Vietnamese Restaurant
47,Brooklyn,Bensonhurst,40.611009,-73.995180,82.0,0.090308,49.0,Shabu-Shabu Restaurant
48,Brooklyn,Sunset Park,40.645103,-74.010316,88.0,0.096916,45.0,Thai Restaurant
49,Brooklyn,Greenpoint,40.730201,-73.954241,150.0,0.165198,70.0,Vietnamese Restaurant
50,Brooklyn,Gravesend,40.595260,-73.973471,53.0,0.058370,26.0,Restaurant
51,Brooklyn,Brighton Beach,40.576825,-73.965094,83.0,0.091410,43.0,Russian Restaurant
52,Brooklyn,Sheepshead Bay,40.586890,-73.943186,76.0,0.083700,33.0,Turkish Restaurant
53,Brooklyn,Manhattan Terrace,40.614433,-73.957438,74.0,0.081498,39.0,Steakhouse Restaurant
54,Brooklyn,Flatbush,40.636326,-73.958401,71.0,0.078194,42.0,Seafood Restaurant
55,Brooklyn,Crown Heights,40.670829,-73.943291,68.0,0.074890,34.0,Pizza Restaurant
56,Brooklyn,East Flatbush,40.641718,-73.936103,19.0,0.020925,8.0,Food Truck Restaurant
57,Brooklyn,Kensington,40.642382,-73.980421,86.0,0.094714,40.0,Thai Restaurant
58,Brooklyn,Windsor Terrace,40.656946,-73.980073,77.0,0.084802,37.0,Thai Restaurant
59,Brooklyn,Prospect Heights,40.676822,-73.964859,132.0,0.145374,75.0,Vietnamese Restaurant
60,Brooklyn,Brownsville,40.663950,-73.910235,56.0,0.061674,35.0,Spanish Restaurant
61,Brooklyn,Williamsburg,40.707144,-73.958115,81.0,0.089207,45.0,Thai Restaurant
62,Brooklyn,Bushwick,40.698116,-73.925258,115.0,0.126652,50.0,Vegetarian / Vegan Restaurant
63,Brooklyn,Bedford Stuyvesant,40.687232,-73.941785,82.0,0.090308,39.0,Seafood Restaurant
64,Brooklyn,Brooklyn Heights,40.695864,-73.993782,149.0,0.164097,63.0,Vietnamese Restaurant
65,Brooklyn,Cobble Hill,40.687920,-73.998561,150.0,0.165198,70.0,Yemeni Restaurant
66,Brooklyn,Carroll Gardens,40.680540,-73.994654,150.0,0.165198,73.0,Thai Restaurant
67,Brooklyn,Red Hook,40.676253,-74.012759,61.0,0.067181,20.0,Thai Restaurant
68,Brooklyn,Gowanus,40.673931,-73.994441,116.0,0.127753,52.0,Thai Restaurant
69,Brooklyn,Fort Greene,40.688527,-73.972906,118.0,0.129956,62.0,Vietnamese Restaurant
70,Brooklyn,Park Slope,40.672321,-73.977050,115.0,0.126652,58.0,Vietnamese Restaurant
71,Brooklyn,Cypress Hills,40.682391,-73.876616,68.0,0.074890,39.0,Spanish Restaurant
72,Brooklyn,East New York,40.669926,-73.880699,20.0,0.022026,9.0,Spanish Restaurant
73,Brooklyn,Starrett City,40.647589,-73.879370,11.0,0.012115,4.0,Pizza Restaurant
74,Brooklyn,Canarsie,40.635564,-73.902093,6.0,0.006608,3.0,Thai Restaurant
75,Brooklyn,Flatlands,40.630446,-73.929113,18.0,0.019824,7.0,Fast Food Restaurant
76,Brooklyn,Mill Island,40.606336,-73.908186,2.0,0.002203,0.0,0
77,Brooklyn,Manhattan Beach,40.577914,-73.943537,19.0,0.020925,8.0,Sandwich Restaurant
78,Brooklyn,Coney Island,40.574293,-73.988683,53.0,0.058370,22.0,Seafood Restaurant
79,Brooklyn,Bath Beach,40.599519,-73.998752,98.0,0.107930,48.0,Turkish Restaurant
80,Brooklyn,Borough Park,40.633131,-73.990498,69.0,0.075991,29.0,Seafood Restaurant
81,Brooklyn,Dyker Heights,40.619219,-74.019314,58.0,0.063877,28.0,Thai Restaurant
82,Brooklyn,Gerritsen Beach,40.590848,-73.930102,21.0,0.023128,6.0,Seafood Restaurant
83,Brooklyn,Marine Park,40.609748,-73.931344,8.0,0.008811,3.0,Pizza Restaurant
84,Brooklyn,Clinton Hill,40.693229,-73.967843,149.0,0.164097,77.0,Vietnamese Restaurant
85,Brooklyn,Sea Gate,40.576375,-74.007873,6.0,0.006608,1.0,American Restaurant
86,Brooklyn,Downtown,40.690844,-73.983463,149.0,0.164097,74.0,Thai Restaurant
87,Brooklyn,Boerum Hill,40.685683,-73.983748,144.0,0.158590,66.0,Thai Restaurant
88,Brooklyn,Prospect Lefferts Gardens,40.658420,-73.954899,99.0,0.109031,56.0,Spanish Restaurant
89,Brooklyn,Ocean Hill,40.678403,-73.913068,73.0,0.080396,37.0,Southern / Soul Food Restaurant
90,Brooklyn,City Line,40.678570,-73.867976,87.0,0.095815,46.0,Thai Restaurant
91,Brooklyn,Bergen Beach,40.615150,-73.898556,6.0,0.006608,0.0,0
92,Brooklyn,Midwood,40.625596,-73.957595,61.0,0.067181,33.0,Seafood Restaurant
93,Brooklyn,Prospect Park South,40.647009,-73.962613,103.0,0.113436,51.0,Thai Restaurant
94,Brooklyn,Georgetown,40.623845,-73.916075,27.0,0.029736,11.0,Seafood Restaurant
95,Brooklyn,East Williamsburg,40.708492,-73.938858,116.0,0.127753,45.0,Vegetarian / Vegan Restaurant
96,Brooklyn,North Side,40.714823,-73.958809,149.0,0.164097,77.0,Vegetarian / Vegan Restaurant
97,Brooklyn,South Side,40.710861,-73.958001,149.0,0.164097,85.0,Vietnamese Restaurant
98,Brooklyn,Ocean Parkway,40.613060,-73.968367,68.0,0.074890,32.0,Steakhouse Restaurant
99,Brooklyn,Fort Hamilton,40.614768,-74.031979,107.0,0.117841,59.0,Thai Restaurant
100,Manhattan,Chinatown,40.715618,-73.994279,150.0,0.165198,70.0,Vietnamese Restaurant
101,Manhattan,Washington Heights,40.851903,-73.936900,135.0,0.148678,64.0,Thai Restaurant
102,Manhattan,Inwood,40.867684,-73.921210,103.0,0.113436,58.0,Steakhouse Restaurant
103,Manhattan,Hamilton Heights,40.823604,-73.949688,109.0,0.120044,70.0,Thai Restaurant
104,Manhattan,Manhattanville,40.816934,-73.957385,98.0,0.107930,56.0,Spanish Restaurant
105,Manhattan,Central Harlem,40.815976,-73.943211,95.0,0.104626,44.0,Southern / Soul Food Restaurant
106,Manhattan,East Harlem,40.792249,-73.944182,93.0,0.102423,54.0,Thai Restaurant
107,Manhattan,Upper East Side,40.775639,-73.960508,147.0,0.161894,68.0,Vegetarian / Vegan Restaurant
108,Manhattan,Yorkville,40.775930,-73.947118,150.0,0.165198,76.0,Vietnamese Restaurant
109,Manhattan,Lenox Hill,40.768113,-73.958860,149.0,0.164097,80.0,Turkish Restaurant
110,Manhattan,Roosevelt Island,40.762160,-73.949168,79.0,0.087004,36.0,Seafood Restaurant
111,Manhattan,Upper West Side,40.787658,-73.977059,150.0,0.165198,91.0,Vietnamese Restaurant
112,Manhattan,Lincoln Square,40.773529,-73.985338,146.0,0.160793,53.0,Thai Restaurant
113,Manhattan,Clinton,40.759101,-73.996119,150.0,0.165198,71.0,Thai Restaurant
114,Manhattan,Midtown,40.754691,-73.981669,149.0,0.164097,65.0,Vietnamese Restaurant
115,Manhattan,Murray Hill M,40.748303,-73.978332,100.0,0.110132,50.0,Vietnamese Restaurant
116,Manhattan,Chelsea M,40.744035,-74.003116,150.0,0.165198,64.0,Thai Restaurant
117,Manhattan,Greenwich Village,40.726933,-73.999914,150.0,0.165198,77.0,Vietnamese Restaurant
118,Manhattan,East Village,40.727847,-73.982226,150.0,0.165198,83.0,Vietnamese Restaurant
119,Manhattan,Lower East Side,40.717807,-73.980890,97.0,0.106828,50.0,Vietnamese Restaurant
120,Manhattan,Tribeca,40.721522,-74.010683,141.0,0.155286,69.0,Vegetarian / Vegan Restaurant
121,Manhattan,Little Italy,40.719324,-73.997305,150.0,0.165198,74.0,Vietnamese Restaurant
122,Manhattan,Soho,40.722184,-74.000657,150.0,0.165198,63.0,Vegetarian / Vegan Restaurant
123,Manhattan,West Village,40.734434,-74.006180,150.0,0.165198,79.0,Seafood Restaurant
124,Manhattan,Manhattan Valley,40.797307,-73.964286,99.0,0.109031,62.0,Vietnamese Restaurant
125,Manhattan,Morningside Heights,40.808000,-73.963896,93.0,0.102423,53.0,Thai Restaurant
126,Manhattan,Gramercy,40.737210,-73.981376,148.0,0.162996,73.0,Thai Restaurant
127,Manhattan,Battery Park City,40.711932,-74.016869,141.0,0.155286,54.0,Steakhouse Restaurant
128,Manhattan,Financial District,40.707107,-74.010665,148.0,0.162996,76.0,Steakhouse Restaurant
129,Queens,Astoria,40.768509,-73.915654,150.0,0.165198,79.0,Vegetarian / Vegan Restaurant
130,Queens,Woodside,40.746349,-73.901842,132.0,0.145374,65.0,Tibetan Restaurant
131,Queens,Jackson Heights,40.751981,-73.882821,128.0,0.140969,69.0,Thai Restaurant
132,Queens,Elmhurst,40.744049,-73.881656,84.0,0.092511,54.0,Vietnamese Restaurant
133,Queens,Howard Beach,40.654225,-73.838138,87.0,0.095815,43.0,Tapas Restaurant
134,Queens,Corona,40.742382,-73.856825,70.0,0.077093,36.0,Sandwich Restaurant
135,Queens,Bay Terrace SI,40.725264,-73.844475,41.0,0.045154,12.0,Thai Restaurant
136,Queens,Kew Gardens,40.705179,-73.829819,103.0,0.113436,47.0,Thai Restaurant
137,Queens,Richmond Hill,40.697947,-73.831833,77.0,0.084802,38.0,Spanish Restaurant
138,Queens,Flushing,40.764454,-73.831773,107.0,0.117841,44.0,Szechuan Restaurant
139,Queens,Long Island City,40.750217,-73.939202,123.0,0.135463,58.0,Thai Restaurant
140,Queens,Sunnyside Q,40.740176,-73.926916,42.0,0.046256,23.0,Seafood Restaurant
141,Queens,East Elmhurst,40.764073,-73.867041,60.0,0.066079,29.0,Seafood Restaurant
142,Queens,Maspeth,40.725427,-73.896217,85.0,0.093612,42.0,Seafood Restaurant
143,Queens,Ridgewood,40.708323,-73.901435,88.0,0.096916,53.0,Vegetarian / Vegan Restaurant
144,Queens,Glendale,40.702762,-73.870742,55.0,0.060573,25.0,Seafood Restaurant
145,Queens,Rego Park,40.728974,-73.857827,92.0,0.101322,50.0,Thai Restaurant
146,Queens,Woodhaven,40.689887,-73.858110,76.0,0.083700,39.0,Thai Restaurant
147,Queens,Ozone Park,40.680708,-73.843203,84.0,0.092511,38.0,Spanish Restaurant
148,Queens,South Ozone Park,40.668550,-73.809865,62.0,0.068282,23.0,Sandwich Restaurant
149,Queens,College Point,40.784903,-73.843045,89.0,0.098018,42.0,Steakhouse Restaurant
150,Queens,Whitestone,40.781291,-73.814202,54.0,0.059471,25.0,Seafood Restaurant
151,Queens,Bayside,40.766041,-73.774274,123.0,0.135463,71.0,Vietnamese Restaurant
152,Queens,Auburndale,40.761730,-73.791762,46.0,0.050661,17.0,Thai Restaurant
153,Queens,Little Neck,40.770826,-73.738898,102.0,0.112335,51.0,Vietnamese Restaurant
154,Queens,Douglaston,40.766846,-73.742498,63.0,0.069383,26.0,Thai Restaurant
155,Queens,Glen Oaks,40.749441,-73.715481,33.0,0.036344,13.0,Sandwich Restaurant
156,Queens,Bellerose,40.728573,-73.720128,52.0,0.057269,24.0,Seafood Restaurant
157,Queens,Kew Gardens Hills,40.722578,-73.820878,18.0,0.019824,5.0,Sandwich Restaurant
158,Queens,Fresh Meadows,40.734394,-73.782713,64.0,0.070485,28.0,Vegetarian / Vegan Restaurant
159,Queens,Briarwood,40.710935,-73.811748,59.0,0.064978,25.0,Sandwich Restaurant
160,Queens,Jamaica Center,40.704657,-73.796902,94.0,0.103524,41.0,Thai Restaurant
161,Queens,Oakland Gardens,40.745619,-73.754950,64.0,0.070485,32.0,Vietnamese Restaurant
162,Queens,Queens Village,40.718893,-73.738715,46.0,0.050661,22.0,Sandwich Restaurant
163,Queens,Hollis,40.711243,-73.759250,44.0,0.048458,20.0,Seafood Restaurant
164,Queens,South Jamaica,40.696911,-73.790426,26.0,0.028634,13.0,Vegetarian / Vegan Restaurant
165,Queens,St. Albans,40.694445,-73.758676,33.0,0.036344,13.0,Seafood Restaurant
166,Queens,Rochdale,40.675211,-73.772588,13.0,0.014317,6.0,Southern / Soul Food Restaurant
167,Queens,Springfield Gardens,40.666230,-73.760421,15.0,0.016520,4.0,Sandwich Restaurant
168,Queens,Cambria Heights,40.692775,-73.735269,24.0,0.026432,8.0,Restaurant
169,Queens,Rosedale,40.659816,-73.735261,23.0,0.025330,9.0,Sandwich Restaurant
170,Queens,Far Rockaway,40.603134,-73.754980,51.0,0.056167,34.0,Southern / Soul Food Restaurant
171,Queens,Broad Channel,40.603027,-73.820055,5.0,0.005507,1.0,Pizza Restaurant
172,Queens,Breezy Point,40.557401,-73.925512,5.0,0.005507,0.0,0
173,Queens,Steinway,40.775923,-73.902290,72.0,0.079295,33.0,Thai Restaurant
174,Queens,Beechhurst,40.792781,-73.804365,19.0,0.020925,6.0,Restaurant
175,Queens,Bay Terrace Q,40.782843,-73.776802,37.0,0.040749,7.0,Steakhouse Restaurant
176,Queens,Edgemere,40.595642,-73.776133,15.0,0.016520,4.0,Seafood Restaurant
177,Queens,Arverne,40.589144,-73.791992,42.0,0.046256,15.0,Sandwich Restaurant
178,Queens,Rockaway Beach,40.582802,-73.822361,95.0,0.104626,51.0,Vegetarian / Vegan Restaurant
179,Queens,Neponsit,40.572037,-73.857547,28.0,0.030837,10.0,Sandwich Restaurant
180,Queens,Murray Hill Q,40.764126,-73.812763,47.0,0.051762,30.0,Pizza Restaurant
181,Queens,Floral Park,40.741378,-73.708847,39.0,0.042952,20.0,Sandwich Restaurant
182,Queens,Holliswood,40.720957,-73.767142,30.0,0.033040,13.0,Seafood Restaurant
183,Queens,Jamaica Estates,40.716805,-73.787227,32.0,0.035242,15.0,Sandwich Restaurant
184,Queens,Queensboro Hill,40.744572,-73.825809,42.0,0.046256,20.0,Taiwanese Restaurant
185,Queens,Hillcrest,40.723825,-73.797603,35.0,0.038546,15.0,Sandwich Restaurant
186,Queens,Ravenswood,40.761705,-73.931575,79.0,0.087004,49.0,Thai Restaurant
187,Queens,Lindenwood,40.663918,-73.849638,14.0,0.015419,3.0,Pizza Restaurant
188,Queens,Laurelton,40.667884,-73.740256,27.0,0.029736,16.0,Seafood Restaurant
189,Queens,Lefrak City,40.736075,-73.862525,74.0,0.081498,34.0,Steakhouse Restaurant
190,Queens,Belle Harbor,40.576156,-73.854018,45.0,0.049559,13.0,Restaurant
191,Queens,Rockaway Park,40.580343,-73.841534,72.0,0.079295,34.0,Seafood Restaurant
192,Queens,Somerville,40.597711,-73.796648,2.0,0.002203,0.0,0
193,Queens,Brookville,40.660003,-73.751753,1.0,0.001101,0.0,0
194,Queens,Bellaire,40.733014,-73.738892,15.0,0.016520,7.0,Italian Restaurant
195,Queens,North Corona,40.754071,-73.857518,70.0,0.077093,33.0,Thai Restaurant
196,Queens,Forest Hills Gardens,40.714611,-73.841022,70.0,0.077093,30.0,Sandwich Restaurant
197,Staten Island,St. George,40.644982,-74.079353,60.0,0.066079,19.0,Tapas Restaurant
198,Staten Island,New Brighton,40.640615,-74.087017,24.0,0.026432,5.0,Mexican Restaurant
199,Staten Island,Stapleton,40.626928,-74.077902,39.0,0.042952,14.0,Sri Lankan Restaurant
200,Staten Island,Sunnyside SI,40.615305,-74.069805,29.0,0.031938,12.0,Sandwich Restaurant
201,Staten Island,West Brighton,40.631879,-74.107182,43.0,0.047357,21.0,Sandwich Restaurant
202,Staten Island,Grymes Hill,40.624185,-74.087248,3.0,0.003304,0.0,0
203,Staten Island,Todt Hill,40.597069,-74.111329,1.0,0.001101,0.0,0
204,Staten Island,South Beach,40.580247,-74.079553,8.0,0.008811,0.0,0
205,Staten Island,Port Richmond,40.633669,-74.129434,49.0,0.053965,23.0,Thai Restaurant
206,Staten Island,Mariner's Harbor,40.632546,-74.150085,6.0,0.006608,1.0,Italian Restaurant
207,Staten Island,Port Ivory,40.639683,-74.174645,1.0,0.001101,0.0,0
208,Staten Island,Castleton Corners,40.613336,-74.119181,14.0,0.015419,8.0,Sandwich Restaurant
209,Staten Island,New Springville,40.594252,-74.164960,22.0,0.024229,7.0,Sandwich Restaurant
210,Staten Island,Travis,40.586314,-74.190737,13.0,0.014317,0.0,0
211,Staten Island,New Dorp,40.572572,-74.116479,39.0,0.042952,21.0,Vietnamese Restaurant
212,Staten Island,Oakwood,40.558462,-74.121566,5.0,0.005507,0.0,0
213,Staten Island,Great Kills,40.549480,-74.149324,19.0,0.020925,8.0,Spanish Restaurant
214,Staten Island,Eltingville,40.542231,-74.164331,33.0,0.036344,17.0,Sandwich Restaurant
215,Staten Island,Annadale,40.538114,-74.178549,11.0,0.012115,6.0,Restaurant
216,Staten Island,Woodrow,40.541968,-74.205246,17.0,0.018722,8.0,Pizza Restaurant
217,Staten Island,Tottenville,40.505334,-74.246569,7.0,0.007709,2.0,Mexican Restaurant
218,Staten Island,Tompkinsville,40.637316,-74.080554,63.0,0.069383,25.0,Spanish Restaurant
219,Staten Island,Silver Lake,40.619193,-74.096290,4.0,0.004405,2.0,Burger Restaurant
220,Staten Island,Sunnyside,40.612760,-74.097126,57.0,0.062775,27.0,Pizza Restaurant
221,Brooklyn,Ditmas Park,40.643675,-73.961013,100.0,0.110132,51.0,Tibetan Restaurant
222,Brooklyn,Wingate,40.660947,-73.937187,72.0,0.079295,44.0,Seafood Restaurant
223,Brooklyn,Rugby,40.655572,-73.926882,67.0,0.073789,51.0,Seafood Restaurant
224,Staten Island,Park Hill,40.609190,-74.080157,6.0,0.006608,1.0,Coffee Restaurant
225,Staten Island,Westerleigh,40.621090,-74.133041,40.0,0.044053,17.0,Thai Restaurant
226,Staten Island,Graniteville,40.620172,-74.153152,3.0,0.003304,0.0,0
227,Staten Island,Arlington,40.635325,-74.165104,6.0,0.006608,1.0,American Restaurant
228,Staten Island,Arrochar,40.596313,-74.067124,25.0,0.027533,10.0,Sandwich Restaurant
229,Staten Island,Grasmere,40.598268,-74.076674,23.0,0.025330,6.0,Vegetarian / Vegan Restaurant
230,Staten Island,Old Town,40.596329,-74.087511,21.0,0.023128,7.0,Restaurant
231,Staten Island,Dongan Hills,40.588673,-74.096399,29.0,0.031938,14.0,Sandwich Restaurant
232,Staten Island,Midland Beach,40.573527,-74.093483,11.0,0.012115,3.0,Russian Restaurant
233,Staten Island,Grant City,40.576216,-74.105856,42.0,0.046256,21.0,Pizza Restaurant
234,Staten Island,New Dorp Beach,40.564255,-74.104327,11.0,0.012115,4.0,Restaurant
235,Staten Island,Bay Terrace,40.553988,-74.139166,8.0,0.008811,2.0,Japanese Restaurant
236,Staten Island,Huguenot,40.531912,-74.191741,10.0,0.011013,5.0,Sandwich Restaurant
237,Staten Island,Pleasant Plains,40.524699,-74.219831,15.0,0.016520,5.0,Pizza Restaurant
238,Staten Island,Butler Manor,40.506082,-74.229504,6.0,0.006608,0.0,0

In [139]:
nbhoods_new.to_csv('working_dataframe.csv', index=False)

In [140]:
venues_no_dups.to_csv('foursqaure_and_yelp_venues.csv')

In [149]:
#Find top venue category by Foursquare and Yelp for each nbhood

,Neighborhood,Venue Category,Venue,Venue Latitude,Venue Longitude
0,Allerton,American Restaurant,1,1,1
1,Allerton,Bakery,3,3,3
2,Allerton,Bar,1,1,1
3,Allerton,Breakfast Restaurant,1,1,1
4,Allerton,Bus Stop,1,1,1
...,...,...,...,...,...
10342,Yorkville,Thai Restaurant,2,2,2
10343,Yorkville,Video Store,1,1,1
10344,Yorkville,Vietnamese Restaurant,2,2,2
10345,Yorkville,Wine Place,5,5,5
10346,Yorkville,Wings Joint,1,1,1

In [153]:
venues=pd.read_csv('foursqaure_and_yelp_venues.csv')

In [161]:
grouped_venues=venues.groupby(['Neighborhood', 'Venue Category'], as_index=False).count().sort_values(by=['Venue'], ascending=False)

In [162]:
grouped_venues=grouped_venues[['Neighborhood','Venue Category','Venue']].groupby(['Neighborhood']).max().sort_values(by=['Venue'], ascending=False)

In [163]:
grouped_venues

                                            Venue Category  Venue
Neighborhood
Murray Hill                          Venues & Event Spaces     29
Midtown South                                  Yoga Studio     28
Murray Hill Q                                  Supermarket     23
West Village                                    Wine Place     20
Greenpoint                                     Yoga Studio     19
Bushwick                                        Wine Place     19
Belmont                                        Wings Joint     18
Gowanus                                        Yoga Studio     18
Greenwich Village                              Yoga Studio     17
South Side                                     Yoga Studio     17
Erasmus                                        Yoga Studio     17
Bensonhurst                                     Vietnamese     16
Soho                                         Women's Store     16
Yorkville                                      Wings Joint     16
East Williamsburg                               Wine Place     16
Carroll Gardens                                Wings Joint     16
North Side                                     Yoga Studio     15
Chinatown                                       Wine Place     15
Jackson Heights                                 Wine Place     15
East Village                                    Wine Place     15
Lenox Hill                                   Women's Store     14
Tribeca                                         Wine Place     14
Bedford Stuyvesant                              Wine Place     14
Flatiron                                       Yoga Studio     14
Financial District                           Women's Store     14
Astoria                                         Wine Place     14
Cobble Hill                                    Yoga Studio     14
Fort Hamilton                                   Wine Place     13
Gramercy                                       Yoga Studio     13
Manhattan Terrace                    Steakhouse Restaurant     12
Battery Park City                            Women's Store     12
East Harlem                                Thai Restaurant     12
Little Neck                                    Wings Joint     12
Melrose                                    Supplement Shop     12
Carnegie Hill                                  Yoga Studio     12
Clinton                                         Wine Place     12
Prospect Heights                               Yoga Studio     12
Long Island City                             Train Station     11
Civic Center                                   Yoga Studio     11
Prospect Lefferts Gardens                       Wine Place     11
Lincoln Square                                 Yoga Studio     11
Kingsbridge Heights                  Vietnamese Restaurant     11
Kingsbridge                                    Wings Joint     11
Douglaston                                     Yoga Studio     11
Little Italy                                 Women's Store     11
Morningside Heights                             Vietnamese     11
Upper West Side                                 Wine Place     11
Concourse                                            Vegan     11
Dumbo                                          Yoga Studio     11
Hammels                                      Walking Tours     11
Sunset Park                                  Women's Store     11
Rockaway Beach                                     Waffles     10
Rockaway Park                                Walking Tours     10
Boerum Hill                                    Yoga Studio     10
Inwood                                         Yoga Studio     10
Oakland Gardens                                Yoga Studio     10
Turtle Bay                                      Wine Place     10
Westchester Square                        Video Game Store     10
Kensington                                           Uzbek     10
Upper East Side                                Yoga Studio     10
Downtown                                       Yoga Studio      9
Hamilton Heights                               Yoga Studio      9
Dyker Heights                                   Wine Place      9
Rugby                                          Wings Joint      9
Midwood                                   Video Game Store      9
Hudson Yards                                    Wine Place      9
Howard Beach                                    Wine Place      9
Hunters Point                                  Yoga Studio      9
Flatbush                                             Vegan      9
Manhattanville                                  Wine Place      9
Fresh Meadows                                      Waffles      9
Prospect Park South                          Women's Store      9
Flushing                                       Yoga Studio      9
Queensboro Hill                       Taiwanese Restaurant      9
Midtown                                      Women's Store      9
Ditmas Park                                    Yoga Studio      9
Clinton Hill                                   Yoga Studio      9
Weeksville                                        Szechuan      9
Brooklyn Heights                               Yoga Studio      9
Whitestone                                   Walking Tours      9
Sutton Place                                   Yoga Studio      9
Bay Ridge                            Vietnamese Restaurant      9
Chelsea M                                    Women's Store      9
Windsor Terrace                                 Wine Place      9
Brighton Beach                                       Wraps      9
Stuyvesant Town                                 Wine Place      9
Sunnyside Gardens                               Wine Place      9
Crown Heights                                   Wine Place      9
South Ozone Park                             Walking Tours      9
Concourse Village                          Supplement Shop      9
Ridgewood                    Vegetarian / Vegan Restaurant      8
Utopia                                                 Spa      8
Grant City                                     Wings Joint      8
Brownsville                                          Trail      8
Glendale                                     Walking Tours      8
Park Slope                                     Yoga Studio      8
Jamaica Hills                              Thai Restaurant      8
Bedford Park                                 Train Station      8
Fulton Ferry                                    Wine Place      8
Kew Gardens                                  Train Station      8
Tudor City                                     Yoga Studio      8
Woodside                                     Train Station      8
Tompkinsville                       Thrift / Vintage Store      8
Noho                                           Yoga Studio      8
Middle Village                               Walking Tours      8
Maspeth                                              Tacos      8
Bath Beach                                      Vietnamese      8
High  Bridge                                    Venezuelan      8
Ocean Parkway                        Steakhouse Restaurant      8
Queensbridge                                         Tacos      8
Homecrest                                    Women's Store      8
Lower East Side                                Yoga Studio      8
Washington Heights                           Women's Store      8
Blissville                                         Waffles      8
Morris Park                                          Vegan      8
Wingate                                         Wine Place      8
Rego Park                            Venues & Event Spaces      8
Vinegar Hill                                    Wine Place      7
Neponsit                                             Vegan      7
Bellerose                                       Wine Place      7
Mount Hope                                Video Game Store      7
Belle Harbor                                         Vegan      7
Bayside                                        Yoga Studio      7
Bay Terrace SI                                 Yoga Studio      7
Longwood                                        Wine Place      7
Mott Haven                           Venues & Event Spaces      7
Morrisania                           Steakhouse Restaurant      7
Arverne                                         Wine Place      7
Marble Hill                                    Yoga Studio      7
Woodhaven                                          Waffles      7
Hollis                                               Vegan      7
Norwood                                        Sports Bars      7
Parkchester                                  Women's Store      7
Queens Village                                       Vegan      7
Far Rockaway                                         Vegan      7
Fordham                                      Women's Store      7
Elmhurst                             Vietnamese Restaurant      7
Elm Park                                        Wine Place      7
College Point                                      Waffles      7
Fort Greene                                    Yoga Studio      7
Unionport                                   Street Vendors      7
University Heights                             Wings Joint      7
St. George                                Toy / Game Store      7
City Line                                 Video Game Store      7
Ozone Park                                   Walking Tours      7
Corona                                         Supermarket      7
Cypress Hills                                  Supermarket      7
Briarwood                                            Tacos      7
Van Nest                                             Vegan      7
Borough Park                                         Tacos      7
Mill Basin                                           Tacos      6
Roosevelt Island                                Wine Place      6
Woodlawn                                     Train Station      6
Manhattan Valley                               Yoga Studio      6
Sheepshead Bay                                 Yoga Studio      6
North Corona                               Thai Restaurant      6
Williamsburg                                   Yoga Studio      6
Richmond Hill                                Walking Tours      6
Port Richmond                                   Vape Shops      6
Holliswood                                           Vegan      6
New Brighton                                    Playground      6
Bronxdale                                      Sports Bars      6
Ocean Hill                                           Vegan      6
Lefrak City                                Warehouse Store      6
Laurelton                                            Vegan      6
Mount Eden                                Video Game Store      6
Murray Hill M                                  Yoga Studio      6
Central Harlem                                  Wine Place      6
Olinville                                            Wraps      5
Sunnyside Q                                        Theater      5
Morris Heights                                       Vegan      5
Red Hook                                        Wine Place      5
Williamsbridge                                       Wraps      5
Ravenswood                                         Turkish      5
Sunnyside                                       Wine Place      5
Steinway                                     Women's Store      5
Allerton                                             Vegan      5
East Tremont                                   Supermarket      5
Floral Park                                          Vegan      5
Broadway Junction                           Street Vendors      5
Auburndale                                   Train Station      5
East Elmhurst                                Walking Tours      5
Gravesend                                       Tapas Bars      5
Claremont Village                    Steakhouse Restaurant      5
Grasmere                     Vegetarian / Vegan Restaurant      5
Jamaica Center                             Thai Restaurant      5
Clason Point                                          Pool      4
Clifton                                      Train Station      4
Old Town                                       Video Store      4
Bulls Head                                     Wings Joint      4
Rosedale                                             Vegan      4
Glen Oaks                                            Vegan      4
Riverdale                                            Vegan      4
Pelham Bay                                 Thai Restaurant      4
Pelham Parkway                                       Track      4
Eltingville                                  Train Station      4
City Island                                     Wine Place      4
Edgewater Park                                  Sports Bar      4
Eastchester                             Seafood Restaurant      4
Bay Terrace Q                                Women's Store      4
Hillcrest                                         Tea Room      4
St. Albans                                           Vegan      4
West Farms                                         Spanish      4
Westerleigh                                     Wine Place      4
Forest Hills Gardens                            Wine Place      4
Coney Island                                Street Vendors      4
Schuylerville                                        Vegan      4
Madison                                                Spa      4
Stapleton                                    Train Station      3
Dongan Hills                                 Train Station      3
Flatlands                                      Video Store      3
South Jamaica                Vegetarian / Vegan Restaurant      3
Shore Acres                                    Yoga Studio      3
Remsen Village                                 Supermarket      3
Country Club                                         Trail      3
Spuyten Duyvil                             Thai Restaurant      3
Rossville                                 Pizza Restaurant      3
East New York                               Street Vendors      3
Starrett City                             Pizza Restaurant      3
Forest Hills                               Thai Restaurant      3
Pleasant Plains                                 Toll Plaza      3
Arrochar                                       Supermarket      3
Cambria Heights                                      Vegan      3
New Lots                                Salon / Barbershop      3
West Brighton                                  Wings Joint      3
Jamaica Estates                        Sandwich Restaurant      3
North Riverdale                     Thrift / Vintage Store      3
Kew Gardens Hills                              Supermarket      3
Baychester                                     Supermarket      3
Breezy Point                                         Trail      3
Great Kills                                  Train Station      3
New Dorp                             Vietnamese Restaurant      3
Travis                                         Sports Club      3
Pelham Gardens                          Spanish Restaurant      3
Soundview                                      Video Store      3
Pomonok                                        Supermarket      3
Castleton Corners                            Tattoo Parlor      3
Georgetown                                Video Game Store      3
Springfield Gardens                             Shoe Store      2
Bay Terrace                                    Supermarket      2
Arlington                                             Deli      2
Woodrow                                   Pizza Restaurant      2
Chelsea SI                           Steakhouse Restaurant      2
Bergen Beach                                    Playground      2
Beechhurst                                     Supermarket      2
Bellaire                                       Supermarket      2
Charleston                                Video Game Store      2
Wakefield                              Sandwich Restaurant      2
Co-op City                              Salon / Barbershop      2
Butler Manor                                          Pool      2
Sunnyside SI                                   Video Store      2
Throgs Neck                                     Sports Bar      2
South Beach                                           Pier      2
Midland Beach                           Russian Restaurant      2
Fox Hills                              Sandwich Restaurant      2
Manhattan Beach                        Sandwich Restaurant      2
Grymes Hill                                        Dog Run      2
Highland Park                                 Tennis Court      2
New Springville                                 Soup Place      2
New Dorp Beach                                  Sports Bar      2
Park Hill                                            Hotel      2
Huguenot                                     Train Station      2
Gerritsen Beach                         Seafood Restaurant      2
Hunts Point                                 Waste Facility      2
Annadale                                     Train Station      2
Port Morris                               Storage Facility      2
Prince's Bay                              Pizza Restaurant      2
Greenridge                     Professional & Other Places      2
Mariner's Harbor                               Supermarket      2
Edgemere                                        Skate Park      2
Sandy Ground                                     Racetrack      2
Richmond Valley                              Train Station      2
Manor Heights                             Pizza Restaurant      2
Rochdale                   Southern / Soul Food Restaurant      2
East Flatbush                                   Wine Place      2
Willowbrook                                            Spa      1
Arden Heights                             Pizza Restaurant      1
Heartland Village                            Shopping Mall      1
Mill Island                                           Pool      1
Bayswater                                     Tennis Court      1
Marine Park                               Pizza Restaurant      1
Malba                        Vegetarian / Vegan Restaurant      1
Lindenwood                              Weight Loss Center      1
Astoria Heights                                Supermarket      1
Bloomfield                               Recreation Center      1
Somerville                                            Park      1
Paerdegat Basin                               Home Service      1
Broad Channel                          Sporting Goods Shop      1
Fieldston                                            Vegan      1
Sea Gate                                       Video Store      1
Roxbury                                              Trail      1
Concord                             Thrift / Vintage Store      1
Edenwald                                       Supermarket      1
Richmond Town                                          Spa      1
Egbertville                             Italian Restaurant      1
Randall Manor                                   Playground      1
Todt Hill                                             Park      1
Oakwood                                      Women's Store      1
Port Ivory                                Recording Studio      1
Tottenville                         Thrift / Vintage Store      1
Castle Hill                                    Supermarket      1